'use client';
import { ArrowDown, ArrowUpRight, Check, Menu, X } from 'lucide-react';
import { motion, useScroll, useTransform } from 'framer-motion';
import Link from 'next/link';
import { useEffect, useState } from 'react';

const copy = {
 de:{nav:['Leistungen','Ablauf','Konditionen','Über uns'],eyebrow:'Creator Management · Europa',titleA:'Aus Aufmerksamkeit',titleB:'wird Einkommen.',intro:'Wir helfen Frauen 35+, eine zahlende Fanbase auf Subscription-Plattformen aufzubauen – mit Strategie, Klarheit und ohne falsche Versprechen.',apply:'Kostenlos bewerben',terms:'Konditionen ansehen',note:'Du bestimmst deinen Content. Immer.',funnel:'Der Weg zu zahlenden Fans',why:'Social Media ist, wie man dich findet. Deine Subscription-Seite ist, wo du verdienst.',services:'Was wir für dich tun',process:'Eine klare Zusammenarbeit. Keine Blackbox.',for:'Gemacht für Frauen, die später einsteigen – mit Absicht.',cta:'Bereit für ein ehrliches Gespräch?',ctaSub:'Die Bewerbung ist kostenlos und verpflichtet dich zu nichts.'},
 en:{nav:['Services','Process','Terms','About'],eyebrow:'Creator management · Europe',titleA:'Turn attention',titleB:'into income.',intro:'We help women 35+ build a paying audience on subscription platforms – with strategy, clarity and no false promises.',apply:'Apply for free',terms:'View our terms',note:'You decide what you create. Always.',funnel:'The path to paying fans',why:'Social media is where people find you. Your subscription page is where you earn.',services:'What we do for you',process:'A clear partnership. No black box.',for:'Built for women starting later – by design.',cta:'Ready for an honest conversation?',ctaSub:'Applying is free and comes with no obligation.'},
 es:{nav:['Servicios','Proceso','Condiciones','Nosotros'],eyebrow:'Gestión de creadoras · Europa',titleA:'Convierte atención',titleB:'en ingresos.',intro:'Ayudamos a mujeres de 35+ a crear una audiencia de pago, con estrategia, claridad y sin falsas promesas.',apply:'Solicitar gratis',terms:'Ver condiciones',note:'Tú decides tu contenido. Siempre.',funnel:'El camino hacia fans de pago',why:'Las redes son donde te encuentran. Tu página de suscripción es donde ganas.',services:'Lo que hacemos por ti',process:'Una colaboración clara. Sin secretos.',for:'Creado para mujeres que empiezan más tarde.',cta:'¿Lista para hablar con honestidad?',ctaSub:'La solicitud es gratuita y sin compromiso.'},
 fr:{nav:['Services','Parcours','Conditions','À propos'],eyebrow:'Management de créatrices · Europe',titleA:"L’attention devient",titleB:'un revenu.',intro:'Nous aidons les femmes de 35 ans et plus à créer une audience payante, avec stratégie, clarté et sans fausses promesses.',apply:'Postuler gratuitement',terms:'Voir les conditions',note:'Vous décidez de votre contenu. Toujours.',funnel:'Le parcours vers les fans payants',why:'Les réseaux vous font connaître. Votre page d’abonnement génère vos revenus.',services:'Ce que nous faisons',process:'Une collaboration claire. Sans zone floue.',for:'Pensé pour celles qui commencent plus tard.',cta:'Prête pour une conversation honnête ?',ctaSub:'La candidature est gratuite et sans engagement.'}
} as const;
const services=[['01','Social Growth','Strategie für TikTok, Instagram, X und Facebook – ausgerichtet auf echte Conversion.'],['02','Content Direction','Ideen, Hooks, Captions und ein Plan, der zu dir und deinen Grenzen passt.'],['03','Funnel Design','Profile, Links und Wege, die aus Neugier zahlende Abonnenten machen.'],['04','Performance','Wir messen Abos und Umsatz – nicht nur Views, Likes oder Eitelkeitsmetriken.'],['05','1:1 Strategy','Regelmäßige Calls mit einer echten Person und Entscheidungen auf Basis echter Zahlen.'],['06','Positioning','Eine unverwechselbare Marke, die deine Erfahrung zum Vorteil macht.']];
const steps=[['01','Bewerben','Kostenlos und unverbindlich.'],['02','Kennenlernen','Ziele, Grenzen und realistische Erwartungen.'],['03','Strategie','Ein klarer Plan und transparente Vereinbarung.'],['04','Wachstum','Du erstellst Content, wir steuern das System.'],['05','Optimierung','Echte Zahlen ansehen und kontinuierlich anpassen.']];
export default function Home(){const[lang,setLang]=useState<keyof typeof copy>('de');const[menu,setMenu]=useState(false);const{scrollYProgress}=useScroll();const heroY=useTransform(scrollYProgress,[0,.25],[0,100]);useEffect(()=>{const l=navigator.language.slice(0,2);if(l in copy)setLang(l as keyof typeof copy)},[]);const t=copy[lang];return <main>
 <header className="site-header"><Link href="#top" className="logo"><span>P4</span>F</Link><nav className="desktop-nav">{t.nav.map((n,i)=><Link key={n} href={['#services','#process','#terms','#about'][i]}>{n}</Link>)}</nav><div className="header-actions"><select aria-label="Sprache" value={lang} onChange={e=>setLang(e.target.value as keyof typeof copy)}>{Object.keys(copy).map(l=><option key={l} value={l}>{l.toUpperCase()}</option>)}</select><Link href="/bewerben" className="mini-cta">{t.apply}</Link><button className="menu-button" aria-label="Menü öffnen" onClick={()=>setMenu(true)}><Menu/></button></div></header>
 {menu&&<motion.div className="mobile-menu" initial={{y:'-100%'}} animate={{y:0}}><button aria-label="Menü schließen" onClick={()=>setMenu(false)}><X/></button><div>{t.nav.map((n,i)=><Link onClick={()=>setMenu(false)} key={n} href={['#services','#process','#terms','#about'][i]}>{n}<ArrowUpRight/></Link>)}</div><Link href="/bewerben" className="button light">{t.apply}</Link></motion.div>}
 <section id="top" className="hero"><motion.div className="hero-orbit" style={{y:heroY}} aria-hidden><span/><span/><span/></motion.div><div className="hero-copy"><p className="eyebrow"><i/>{t.eyebrow}</p><h1><span>{t.titleA}</span><em>{t.titleB}</em></h1><p className="hero-intro">{t.intro}</p><div className="hero-actions"><Link className="button dark" href="/bewerben">{t.apply}<ArrowUpRight/></Link><Link href="#terms" className="text-link">{t.terms}<ArrowDown/></Link></div></div><div className="hero-foot"><span>18+</span><p>{t.note}</p><div>DE · EN · ES · FR</div></div></section>
 <section className="funnel-section"><div className="section-head"><p className="eyebrow"><i/>{t.funnel}</p><h2>{t.why}</h2></div><div className="funnel">{['Reach','Profile','Click','Subscribe','Revenue'].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong>{i<4&&<b>→</b>}</div>)}</div></section>
 <section id="services" className="services-section"><div className="section-number">01 — SERVICES</div><h2>{t.services}</h2><div className="service-grid">{services.map(([no,title,text])=><article key={no}><span>{no}</span><h3>{title}</h3><p>{text}</p><ArrowUpRight/></article>)}</div></section>
 <section id="about" className="manifesto"><div className="manifesto-kicker">35+</div><div><p className="eyebrow light-text"><i/>OUR FOCUS</p><h2>{t.for}</h2><p>Deine Erfahrung und Persönlichkeit sind kein Nachteil, sondern deine stärkste Positionierung. Wir kümmern uns um Plattformen, Prozesse und Zahlen.</p><Link className="text-link aqua" href="/ueber-uns">Unsere Haltung kennenlernen <ArrowUpRight/></Link></div></section>
 <section id="process" className="process-section"><div className="section-number">02 — PROCESS</div><h2>{t.process}</h2><div className="steps">{steps.map(([no,title,text])=><article key={no}><span>{no}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section id="terms" className="terms-section"><div><p className="eyebrow"><i/>TRANSPARENZ</p><h2>Was du vorher wissen solltest.</h2></div><div className="term-list">{['Keine Einkommensgarantien','Du kontrollierst deinen Content','Klare Konditionen im Vertrag','Vertraulicher Umgang mit deinen Daten'].map(x=><div key={x}><Check/><span>{x}</span></div>)}<Link href="/konditionen" className="text-link">Alle Konditionen lesen <ArrowUpRight/></Link></div></section>
 <section className="final-cta"><p>P4F / EUROPE</p><h2>{t.cta}</h2><span>{t.ctaSub}</span><Link href="/bewerben" className="button light">{t.apply}<ArrowUpRight/></Link></section>
 <footer><Link href="#top" className="logo"><span>P4</span>F</Link><p>Creator Management für Frauen 35+.<br/>Klar. Persönlich. Auf Augenhöhe.</p><div><Link href="/impressum">Impressum</Link><Link href="/datenschutz">Datenschutz</Link><Link href="/nutzungsbedingungen">Nutzungsbedingungen</Link></div><div><a href="mailto:contact@prom4fans.com">contact@prom4fans.com</a><span>© 2026 Prom4Fans</span></div></footer>
 </main>}
