import Link from 'next/link';
import type { Locale } from '@/lib/i18n';

export function PricingSection({ locale }: { locale: Locale }) {
  const en = locale === 'en';
  const plans = en ? [
    { name: 'Growth Support', price: '10%', note: 'of agreed subscription revenue', text: 'For creators who produce their own content but want strategy, ideas and ongoing support.', items: ['Regular content ideas', 'Social strategy across Instagram, TikTok, X & more', 'Profile and content optimisation', 'Performance reviews and conversion recommendations'], cta: 'Ask about Growth Support' },
    { name: 'Full Management', price: '30%', note: 'of agreed subscription revenue', text: 'For creators who want to hand over more of the operational work and focus on creating.', items: ['Everything in Growth Support', 'Operational social media management', 'Content planning and editing', 'Ongoing optimisation and close support'], cta: 'Ask about Full Management' },
  ] : [
    { name: 'Growth Support', price: '10 %', note: 'der vereinbarten Subscription-Einnahmen', text: 'Für Creator, die ihren Content selbst umsetzen, aber Strategie, Ideen und laufende Unterstützung möchten.', items: ['Regelmäßige Content-Ideen', 'Strategie für Instagram, TikTok, X & Co.', 'Profil- und Content-Optimierung', 'Performance-Auswertung und Conversion-Empfehlungen'], cta: 'Growth Support anfragen' },
    { name: 'Full Management', price: '30 %', note: 'der vereinbarten Subscription-Einnahmen', text: 'Für Creator, die operative Arbeit abgeben und sich stärker auf ihre Content-Produktion konzentrieren möchten.', items: ['Alles aus Growth Support', 'Operatives Social-Media-Management', 'Content-Planung, Schnitt und Aufbereitung', 'Laufende Optimierung und engere Betreuung'], cta: 'Full Management anfragen' },
  ];
  return <section id="pricing" className="bg-[#f3effb] py-20 md:py-28"><div className="mx-auto w-[min(100%-2rem,78rem)]"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#6c35ed]">{en ? 'Clear terms' : 'Klare Konditionen'}</p><h2 className="mt-5 max-w-3xl text-4xl font-black leading-[.98] tracking-[-.04em] text-[#15162d] md:text-6xl">{en ? 'You grow. We grow with you.' : 'Du wächst. Wir wachsen mit.'}</h2><p className="mt-6 max-w-2xl text-lg leading-relaxed text-[#586078]">{en ? 'No expensive agency retainer or hidden fees. Start small, then scale support with your actual needs.' : 'Kein teures Agentur-Abo, keine versteckten Kosten. Der Einstieg bleibt bewusst günstig – danach richtet sich unsere Vergütung nach Umfang und tatsächlichem Erfolg.'}</p><div className="mt-10 rounded-3xl border border-[#ddd7ec] bg-white p-7 md:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h3 className="text-2xl font-black text-[#15162d]">{en ? 'One-time setup & strategy call' : 'Einmaliges Setup & Strategiegespräch'}</h3><p className="mt-2 max-w-2xl text-sm leading-relaxed text-[#586078]">{en ? 'Account analysis, potential check, goals, content and growth strategy, plus a joint video call.' : 'Analyse deiner Accounts, Potenzial-Check, Zieldefinition, Content- und Wachstumsstrategie sowie gemeinsamer Videocall.'}</p></div><div className="shrink-0 text-right"><div className="text-4xl font-black text-[#6c35ed]">30 €</div><div className="text-xs text-[#7b7e92]">{en ? 'one-time at start' : 'einmalig zum Start'}</div></div></div></div><div className="mt-6 grid gap-6 md:grid-cols-2">{plans.map((plan) => <article key={plan.name} className="rounded-3xl bg-[#15162d] p-7 text-white md:p-8"><h3 className="text-2xl font-black">{plan.name}</h3><p className="mt-3 min-h-12 text-sm leading-relaxed text-[#c9cbda]">{plan.text}</p><div className="mt-7 text-5xl font-black text-[#d6fa43]">{plan.price}</div><p className="mt-1 text-xs text-[#c9cbda]">{plan.note}</p><ul className="mt-7 space-y-3 text-sm text-[#f4f2ff]">{plan.items.map((item) => <li key={item} className="flex gap-2"><span className="text-[#d6fa43]">✓</span>{item}</li>)}</ul><Link href="/kontakt" className="mt-8 inline-flex rounded-full bg-white px-5 py-3 text-sm font-bold text-[#15162d] transition hover:bg-[#d6fa43]">{plan.cta}</Link></article>)}</div><p className="mt-6 text-xs leading-relaxed text-[#73768b]">{en ? 'The exact calculation basis (for example net proceeds after platform fees, refunds and taxes) and scope are defined transparently in the contract.' : 'Die genaue Berechnungsgrundlage (z. B. Nettoerlöse nach Plattformgebühren, Rückerstattungen und Steuern) sowie der Leistungsumfang werden vor Beginn transparent im Vertrag festgelegt.'}</p></div></section>;
}
