export type ExtraGuidePage = {
  slug: string;
  category: 'Einstieg' | 'Content' | 'Wachstum' | 'Management' | 'Sicherheit' | 'Analyse';
  eyebrow: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  lead: string;
  shortAnswer: string;
  readingTime: string;
  published: string;
  updated: string;
  sections: Array<{ title: string; paragraphs: string[]; bullets?: string[]; callout?: string }>;
  checklistTitle: string;
  checklist: string[];
  related: string[];
  serviceLinks: Array<{ href: string; label: string; text: string }>;
};

export const extraGuides: Record<string, ExtraGuidePage> = {
  'onlyfans-bio-schreiben': {
    slug: 'onlyfans-bio-schreiben',
    category: 'Einstieg',
    eyebrow: 'OnlyFans Bio',
    title: 'OnlyFans Bio schreiben: in wenigen Zeilen klar machen, warum jemand bleiben sollte',
    metaTitle: 'OnlyFans Bio schreiben: Aufbau, Beispiele & Checkliste',
    metaDescription: 'Eine gute OnlyFans Bio erklärt schnell, was dein Profil besonders macht. Aufbau, Formulierungsregeln, typische Fehler und praktische Checkliste.',
    lead: 'Eine Bio muss nicht clever klingen. Sie muss Orientierung geben: Wer bist du, welche Art von Content erwartet jemanden und warum lohnt es sich, deinem Profil zu folgen?',
    shortAnswer: 'Baue deine Bio aus drei Teilen: klare Positionierung, konkreter Erwartungsrahmen und ein kurzer nächster Schritt. Vermeide austauschbare Aussagen wie „exclusive content“ ohne Kontext. Gute Bios sind verständlich, glaubwürdig und passen sprachlich zu deinem restlichen Auftritt.',
    readingTime: '8 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Eine Bio beantwortet drei Fragen', paragraphs: ['Menschen scannen ein Profil schnell. Deine Bio sollte deshalb beantworten, wer du bist, was regelmäßig erscheint und welche Stimmung oder Perspektive dein Profil auszeichnet. Dafür brauchst du keine lange Selbstdarstellung.', 'Hilfreich ist eine einfache Reihenfolge: erst Wiedererkennung, dann Erwartung, dann Handlung. Ein Satz beschreibt dich, ein Satz macht den Content konkreter und der letzte Teil sagt, was die Person als Nächstes tun kann.'], bullets: ['Wer bist du beziehungsweise wofür stehst du?', 'Welche Inhalte oder Formate sind wiederkehrend?', 'Welche Tonalität erwartet die Community?', 'Was ist der klare nächste Schritt?'] },
      { title: 'Positionierung schlägt allgemeine Versprechen', paragraphs: ['Formulierungen wie „exclusive content“, „daily posts“ oder „something for everyone“ sind leicht austauschbar. Stärker wird die Bio, wenn sie eine erkennbare Perspektive vermittelt: Stil, Alter, Humor, Themen oder ein bestimmtes Format.', 'Die Aussage muss dabei wahr bleiben. Wenn du nur zweimal pro Woche veröffentlichen willst, ist „daily“ keine gute Idee. Eine Bio ist ein Erwartungsvertrag; zu große Versprechen erzeugen später eher Enttäuschung als Bindung.'] },
      { title: 'Schreibe so, wie du auch im Content klingst', paragraphs: ['Die Bio ist Teil deiner Marke. Wenn deine Captions direkt und humorvoll sind, sollte die Bio nicht plötzlich wie ein Werbetext klingen. Wenn dein Auftritt ruhig und hochwertig ist, passen zu viele Emojis oder aggressive Calls-to-Action oft nicht.', 'Lies die Bio laut. Klingt sie nach einem Menschen oder nach einer Vorlage? Entferne alles, was du in einem echten Gespräch niemals sagen würdest. Das ist eine einfache Qualitätskontrolle.'] },
      { title: 'Konkrete Struktur statt Copy-Paste-Vorlage', paragraphs: ['Eine sinnvolle Vorlage ist: „Ich bin … / Hier bekommst du … / Neu: … / Wenn du … suchst, bist du hier richtig.“ Die konkrete Ausgestaltung muss aber zu deinem Profil passen.', 'Nutze Zahlen nur, wenn du sie halten kannst. Ein fester Wochenrhythmus kann vertrauenswürdiger wirken als ein übertriebenes Leistungsversprechen. Ebenso kann eine klare thematische Grenze stärker sein als der Versuch, alles anzubieten.'], callout: 'Die beste Bio ist nicht die mit den meisten Keywords, sondern die, nach der ein neuer Besucher sofort weiß, ob das Profil zu ihm passt.' },
      { title: 'Teste Änderungen einzeln', paragraphs: ['Wenn du Bio, Profilbild, Preis und Content gleichzeitig änderst, weißt du später nicht, was einen Effekt hatte. Ändere lieber eine Sache und beobachte Profilaufrufe, Conversion und Rückmeldungen über einen sinnvollen Zeitraum.', 'Dokumentiere die alte und neue Version. So entsteht mit der Zeit eigenes Wissen darüber, welche Sprache für deine Zielgruppe funktioniert – wertvoller als allgemeine Internetvorlagen.'] },
    ],
    checklistTitle: 'Bio-Check vor dem Speichern',
    checklist: ['Positionierung in einem Satz erkennbar', 'Content-Erwartung konkret beschrieben', 'Keine Versprechen, die du nicht halten kannst', 'Tonalität passt zu deinen Captions', 'Unnötige Füllwörter entfernt', 'Call-to-Action verständlich', 'Bio auf dem Smartphone gegengelesen', 'Änderung für späteren Vergleich dokumentiert'],
    related: ['onlyfans-profil-optimieren', 'creator-positionierung', 'onlyfans-starten'],
    serviceLinks: [{ href: '/de/onlyfans-management', label: 'OnlyFans Management', text: 'Profil, Positionierung und Content-Rhythmus sollten als ein System funktionieren – genau dort setzt unser Management an.' }],
  },
  'onlyfans-preise-festlegen': {
    slug: 'onlyfans-preise-festlegen', category: 'Analyse', eyebrow: 'Preisstrategie',
    title: 'OnlyFans Preise festlegen: eine Preisstrategie, die zu Content und Zielgruppe passt',
    metaTitle: 'OnlyFans Preise festlegen: Preisstrategie für Creator',
    metaDescription: 'OnlyFans Preis festlegen ohne Ratespiel: Positionierung, Leistungsumfang, Tests, Rabatte und Retention sinnvoll zusammen denken.',
    lead: 'Der richtige Preis entsteht nicht aus einer magischen Zahl. Er muss zu Positionierung, Content-Menge, Zielgruppe, Akquise-Kosten und dem langfristigen Wert einer Community passen.',
    shortAnswer: 'Lege zuerst fest, was das Abo konkret enthält und welche Zielgruppe du ansprichst. Wähle dann einen nachvollziehbaren Startpreis, teste nicht ständig und bewerte nicht nur neue Abos, sondern auch Verlängerungen. Ein niedriger Preis ist nicht automatisch leichter zu verkaufen und ein hoher Preis funktioniert nur mit klar erkennbarem Gegenwert.',
    readingTime: '9 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Definiere zuerst das Produkt', paragraphs: ['Bevor du eine Zahl festlegst, musst du wissen, was jemand regelmäßig bekommt. Wie häufig veröffentlichst du? Welche Formate gehören zum Abo? Welche Inhalte bleiben öffentlich, welche sind Teil der Subscription?', 'Je klarer der Leistungsumfang, desto sinnvoller lässt sich ein Preis begründen. Ohne diese Grundlage wird Pricing zum Ratespiel und jede Reaktion führt zu hektischen Änderungen.'] },
      { title: 'Preis und Positionierung müssen zusammenpassen', paragraphs: ['Ein hochwertig inszenierter, klar positionierter Auftritt kommuniziert anders als ein sehr spontanes Profil mit hoher Frequenz. Beides kann funktionieren, aber die Preislogik sollte zum Gesamtbild passen.', 'Achte außerdem darauf, welche Erwartungen dein Traffic mitbringt. Besucher aus sehr breiten Reichweitenkanälen reagieren anders als eine kleinere Community, die dich bereits länger kennt und bewusst wegen deiner Persönlichkeit folgt.'] },
      { title: 'Bewerte Verlängerungen, nicht nur neue Abos', paragraphs: ['Ein Preis kann viele Erstabschlüsse erzeugen und trotzdem langfristig schlecht sein, wenn kaum jemand verlängert. Deshalb solltest du die Entscheidung nicht nur an neuen Subscriptions messen.', 'Sinnvolle Kennzahlen sind Conversion nach Profilbesuch, Anteil der Verlängerungen, durchschnittliche Laufzeit und der Umsatz pro gewonnenem Nutzer über mehrere Monate. Erst gemeinsam zeigen sie, ob die Preisstrategie trägt.'], bullets: ['Conversion nach qualifiziertem Profilbesuch', 'Verlängerungsrate', 'Durchschnittliche Laufzeit', 'Umsatz pro Subscriber über mehrere Monate'] },
      { title: 'Rabatte brauchen einen Zweck', paragraphs: ['Rabatte können einen Einstieg erleichtern, sollten aber nicht zum Dauerzustand werden. Wenn Nutzer lernen, dass jederzeit ein starker Rabatt verfügbar ist, verliert der reguläre Preis an Glaubwürdigkeit.', 'Nutze Promotions gezielt für einen Anlass oder einen Test und dokumentiere, ob rabattierte Nutzer später tatsächlich verlängern. Sonst optimierst du nur auf kurzfristige Abschlüsse.'] },
      { title: 'Teste langsam und dokumentiert', paragraphs: ['Ändere Preise nicht nach einzelnen guten oder schlechten Tagen. Traffic schwankt und kleine Datenmengen täuschen schnell. Halte einen Testzeitraum fest und verändere währenddessen möglichst nicht gleichzeitig Bio, Funnel und Content-Frequenz.', 'Pricing ist kein einmaliges Setup. Wenn sich dein Content, deine Zielgruppe oder dein Markenbild verändert, darf sich auch die Preislogik entwickeln – aber auf Basis echter Daten.'], callout: 'Kein Preis garantiert Umsatz. Entscheidend ist, ob Angebot, Zielgruppe, Traffic und Bindung als Gesamtsystem funktionieren.' },
    ],
    checklistTitle: 'Preisstrategie-Check', checklist: ['Leistungsumfang des Abos klar definiert', 'Zielgruppe beschrieben', 'Startpreis nachvollziehbar begründet', 'Regulärer Preis und Rabatte getrennt betrachtet', 'Conversion und Verlängerungen gemessen', 'Testzeitraum festgelegt', 'Keine parallelen Großänderungen während des Tests', 'Ergebnisse dokumentiert'],
    related: ['creator-kennzahlen', 'onlyfans-profil-optimieren', 'onlyfans-starten'],
    serviceLinks: [{ href: '/de/onlyfans-management', label: 'OnlyFans Management', text: 'Wir betrachten Pricing nicht isoliert, sondern gemeinsam mit Positionierung, Funnel, Content und Retention.' }],
  },
  'content-ideen-fuer-creator': {
    slug: 'content-ideen-fuer-creator', category: 'Content', eyebrow: 'Content Ideen',
    title: 'Content-Ideen für Creator entwickeln, ohne jeden Tag bei null anzufangen',
    metaTitle: 'Content-Ideen für Creator: System statt Ideenstress',
    metaDescription: 'Content-Ideen systematisch entwickeln: Themen-Säulen, Serien, Hooks, Community-Fragen und ein Ideen-Backlog für Creator.',
    lead: 'Gute Ideen entstehen leichter aus einem System als aus Inspiration. Mit wenigen Themen-Säulen, wiederkehrenden Serien und einem laufenden Backlog kannst du aus einer Idee viele Formate machen.',
    shortAnswer: 'Definiere drei bis fünf Themen-Säulen und baue pro Säule wiederkehrende Serien. Sammle Fragen, Reaktionen und Beobachtungen laufend in einem Backlog. Bei der Planung kombinierst du Thema, Format und Perspektive – so entstehen deutlich mehr Ideen, ohne dass du ständig brainstormen musst.',
    readingTime: '9 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Arbeite mit Themen-Säulen', paragraphs: ['Themen-Säulen sind wenige Bereiche, für die dein Profil regelmäßig steht. Sie verhindern, dass jeder Post isoliert wirkt, und helfen der Community zu verstehen, was sie langfristig erwartet.', 'Eine Säule kann Persönlichkeit, Alltag, Expertise, Transformation, Humor oder ein wiederkehrendes visuelles Thema sein. Entscheidend ist nicht die Kategorie selbst, sondern dass sie zu deiner Positionierung passt.'] },
      { title: 'Aus einer Idee werden fünf Formate', paragraphs: ['Nimm eine Kernidee und ändere das Format: kurze Story, Liste, Vorher-Nachher, Meinung, Frage an die Community oder längerer Hintergrund. So musst du nicht für jeden Kanal ein komplett neues Thema erfinden.', 'Das funktioniert besonders gut, wenn du zwischen Discovery-Content, Vertrauens-Content und Conversion-näheren Formaten unterscheidest. Dasselbe Thema kann in jeder Phase anders erzählt werden.'], bullets: ['Kurzer Hook oder Beobachtung', 'Persönliche Geschichte', 'Checkliste oder How-to', 'Meinung oder Perspektive', 'Community-Frage oder Reaktion'] },
      { title: 'Baue Serien statt Einzelposts', paragraphs: ['Serien reduzieren Entscheidungsaufwand. Wenn jeden Dienstag dasselbe Grundformat wiederkehrt, musst du nur noch die konkrete Folge planen. Gleichzeitig entsteht Wiedererkennung.', 'Eine gute Serie ist offen genug für viele Folgen und spezifisch genug, um einen eigenen Charakter zu haben. Nach einigen Wochen kannst du anhand von Saves, Antworten und Klicks entscheiden, welche Serien weiterlaufen.'] },
      { title: 'Die Community liefert ständig Rohmaterial', paragraphs: ['Kommentare, DMs, häufige Fragen und Missverständnisse sind wertvolle Hinweise. Wenn dieselbe Frage mehrfach auftaucht, ist sie wahrscheinlich ein Content-Thema.', 'Sammle diese Signale an einem festen Ort. Antworte nicht nur individuell, sondern überlege, welche Frage sich als öffentlicher Post oder Serie beantworten lässt. So wird Community-Arbeit gleichzeitig Teil deiner Ideenfindung.'] },
      { title: 'Führe ein Backlog mit Status', paragraphs: ['Ein reines Notizdokument wird schnell unübersichtlich. Nutze einfache Status wie „Idee“, „ausarbeiten“, „produktionsbereit“, „veröffentlicht“ und „wiederverwenden“. Das reicht oft völlig.', 'Bei der Wochenplanung ziehst du nicht mehr aus dem Nichts neue Ideen, sondern wählst aus einem gepflegten Vorrat. Das macht Batching deutlich leichter und reduziert Stress.'] },
    ],
    checklistTitle: 'Ideen-System in 20 Minuten', checklist: ['Drei bis fünf Themen-Säulen definiert', 'Mindestens zwei Serien pro Säule notiert', 'Fragen aus DMs und Kommentaren gesammelt', 'Ein zentrales Ideen-Backlog angelegt', 'Status für Ideen festgelegt', 'Ideen in mehrere Formate übersetzt', 'Top-Serien anhand echter Reaktionen bewertet'],
    related: ['content-plan-erstellen', 'content-batching', 'creator-positionierung'], serviceLinks: [{ href: '/de/creator-management', label: 'Creator Management', text: 'Wir verbinden Themen-Säulen, Formate, Produktionsrhythmus und Distribution zu einem belastbaren Content-System.' }],
  },
  'redaktionsplan-fuer-creator': {
    slug: 'redaktionsplan-fuer-creator', category: 'Content', eyebrow: 'Redaktionsplan',
    title: 'Redaktionsplan für Creator: so planst du eine Woche, die du wirklich durchhältst',
    metaTitle: 'Redaktionsplan für Creator: Vorlage & Wochen-System',
    metaDescription: 'Redaktionsplan für Creator: Themen, Formate, Produktionsblöcke, Distribution und Auswertung in einen realistischen Wochenrhythmus bringen.',
    lead: 'Ein Redaktionsplan ist kein Kalender voller Pflichten. Er soll Entscheidungen vorziehen, Produktionszeiten bündeln und trotzdem Platz für spontane Inhalte lassen.',
    shortAnswer: 'Plane zuerst feste Formate und Kapazität, nicht einzelne Posts. Lege pro Woche wenige Prioritäten fest, bündele Produktion in Blöcken und reserviere Platz für spontane Themen. Ein guter Redaktionsplan ist so einfach, dass du ihn auch in einer stressigen Woche noch benutzen kannst.',
    readingTime: '8 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Starte mit verfügbarer Zeit', paragraphs: ['Viele Pläne scheitern, weil zuerst eine ideale Posting-Frequenz gewählt wird und erst danach die verfügbare Zeit betrachtet wird. Drehe die Reihenfolge um. Wie viele Stunden kannst du zuverlässig pro Woche investieren?', 'Teile diese Zeit grob in Ideen, Produktion, Bearbeitung, Veröffentlichung und Community. Dadurch erkennst du früh, ob dein Plan realistisch ist.'] },
      { title: 'Plane Formate vor Themen', paragraphs: ['Wiederkehrende Formate erleichtern Planung und Produktion. Wenn du weißt, dass montags ein kurzer Einstieg, mittwochs eine Serie und freitags ein längerer Beitrag kommt, musst du nur noch das Thema einsetzen.', 'Das schafft gleichzeitig Konsistenz für die Community. Du kannst Formate monatlich überprüfen und schwache Formate ersetzen, statt jede Woche die ganze Strategie neu zu bauen.'] },
      { title: 'Trenne Produktion und Veröffentlichung', paragraphs: ['Du musst nicht an jedem Veröffentlichungstag produzieren. Bündele ähnliche Aufgaben: mehrere Clips drehen, mehrere Captions vorbereiten, mehrere Thumbnails oder Bilder bearbeiten.', 'Die Veröffentlichung kann danach verteilt stattfinden. Dadurch sinkt der Kontextwechsel und du kannst an Produktionstagen gezielter arbeiten.'] },
      { title: 'Plane Distribution mit ein', paragraphs: ['Ein fertiger Post ist nicht automatisch distribuiert. Notiere, auf welchem Kanal welcher Ausschnitt oder Teaser erscheint und wohin er führen soll. So wird dein Redaktionsplan gleichzeitig Teil des Funnels.', 'Achte darauf, nicht überall exakt dasselbe zu kopieren. Ein Thema kann kanalübergreifend gleich bleiben, aber Einstieg, Länge und Call-to-Action sollten zum jeweiligen Umfeld passen.'] },
      { title: 'Nutze eine kleine Review-Schleife', paragraphs: ['Am Ende der Woche reichen zehn Minuten: Was war leicht umzusetzen? Was wurde verschoben? Welche Formate haben echte Reaktionen erzeugt? Welche Aufgaben haben unverhältnismäßig viel Zeit gekostet?', 'Passe den Plan danach an. Ein realistischer Plan wird durch Nutzung besser; ein perfektes Template, das nie gepflegt wird, bringt nichts.'] },
    ],
    checklistTitle: 'Wöchentlicher Redaktionsplan', checklist: ['Verfügbare Zeit festgelegt', 'Wiederkehrende Formate definiert', 'Themen den Formaten zugeordnet', 'Produktionsblöcke reserviert', 'Veröffentlichungen geplant', 'Distribution pro Kanal notiert', 'Puffer für spontane Themen gelassen', 'Wöchentliche Review eingeplant'],
    related: ['content-plan-erstellen', 'content-batching', 'content-ideen-fuer-creator'], serviceLinks: [{ href: '/de/creator-management', label: 'Content-System im Creator Management', text: 'Wir bauen Redaktionsplan, Produktion und Auswertung so zusammen, dass der Rhythmus zu deinem Alltag passt.' }],
  },
  'onlyfans-follower-gewinnen': {
    slug: 'onlyfans-follower-gewinnen', category: 'Wachstum', eyebrow: 'Reichweite aufbauen',
    title: 'OnlyFans Follower gewinnen: Reichweite als Funnel statt als Trick verstehen',
    metaTitle: 'OnlyFans Follower gewinnen: nachhaltiger Reichweiten-Funnel',
    metaDescription: 'OnlyFans Follower gewinnen ohne Tricklisten: Zielgruppe, Discovery-Kanäle, Profil-Conversion, Content-Funnel und Messung sinnvoll verbinden.',
    lead: 'Subscription-Plattformen sind selten der Ort, an dem Menschen dich zum ersten Mal entdecken. Wachstum entsteht deshalb vor allem aus einem funktionierenden Weg von öffentlicher Reichweite zu Vertrauen und schließlich zum Profil.',
    shortAnswer: 'Wähle ein bis zwei öffentliche Kanäle, auf denen deine Zielgruppe wirklich aktiv ist. Produziere dort Content für Aufmerksamkeit und Vertrauen, führe mit klarer Erwartung auf dein Profil und messe den gesamten Weg. Mehr Reichweite bringt wenig, wenn Profil und Angebot nicht konvertieren.',
    readingTime: '10 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Denke in Stufen statt in Plattformen', paragraphs: ['Ein Funnel besteht aus Aufmerksamkeit, Interesse, Vertrauen und Handlung. Unterschiedliche Inhalte erfüllen unterschiedliche Aufgaben. Ein kurzer Clip kann Aufmerksamkeit erzeugen, ein persönlicher Beitrag Vertrauen aufbauen und das Profil die Entscheidung erleichtern.', 'Wenn du jeden Post direkt auf Verkauf optimierst, überspringst du häufig die mittleren Stufen. Besonders kalter Traffic braucht erst Gründe, dir überhaupt länger zu folgen.'] },
      { title: 'Wähle Kanäle nach Zielgruppe und Format', paragraphs: ['Nicht jede Plattform passt zu jeder Person. Entscheidend sind Zielgruppe, Formatstärke und die Frage, ob du den Kanal dauerhaft bedienen kannst. Ein guter Hauptkanal plus ein ergänzender Kanal ist oft besser als fünf halbaktive Accounts.', 'Prüfe außerdem die jeweils aktuellen Plattformregeln für Links und Inhalte. Regeln ändern sich; dein Funnel sollte nicht davon abhängen, dass eine einzelne Plattform jede Form von Weiterleitung dauerhaft erlaubt.'] },
      { title: 'Optimiere die Profil-Conversion', paragraphs: ['Wenn viele Menschen dein öffentliches Profil besuchen, aber kaum jemand den nächsten Schritt macht, ist nicht automatisch mehr Reichweite nötig. Dann liegt der Engpass wahrscheinlich näher am Profil.', 'Prüfe Bio, visuelle Konsistenz, angeheftete Inhalte, Erwartung und Call-to-Action. Neue Besucher müssen schnell verstehen, wer du bist und warum sich der nächste Schritt lohnt.'] },
      { title: 'Baue Vertrauen mit wiederkehrenden Formaten', paragraphs: ['Wiederkehrende Serien schaffen Verlässlichkeit und geben neuen Followern mehrere Kontaktpunkte. Nicht jeder entscheidet beim ersten Video oder Post.', 'Plane deshalb Content, der Menschen einen Grund gibt zurückzukommen: laufende Geschichten, regelmäßige Fragen, Fortschritte, feste Tage oder ein erkennbares Format.'] },
      { title: 'Miss den Engpass', paragraphs: ['Tracke nicht nur Reichweite. Sinnvoller ist eine einfache Kette: Impressionen, Profilbesuche, Link-Klicks, Zielseitenbesuche und Abschlüsse. Die exakten Daten hängen von den verfügbaren Plattform-Statistiken ab.', 'Wenn du weißt, wo die größte Lücke liegt, kannst du gezielt arbeiten. Ohne diese Kette besteht die Gefahr, ständig neue Content-Ideen zu suchen, obwohl das eigentliche Problem die Profil-Conversion ist.'] },
    ],
    checklistTitle: 'Reichweiten-Funnel prüfen', checklist: ['Ein bis zwei Hauptkanäle priorisiert', 'Zielgruppe pro Kanal beschrieben', 'Discovery- und Vertrauens-Content getrennt geplant', 'Profilversprechen klar', 'Call-to-Action verständlich', 'Linkweg getestet', 'Funnel-Kennzahlen regelmäßig notiert', 'Größten Engpass identifiziert'],
    related: ['social-media-funnel', 'onlyfans-profil-optimieren', 'creator-kennzahlen'], serviceLinks: [{ href: '/de/onlyfans-management', label: 'OnlyFans Growth & Management', text: 'Wir verbinden Reichweite, Profil, Content und Reporting zu einem messbaren Funnel statt einzelne Taktiken isoliert zu testen.' }],
  },
  'onlyfans-ohne-instagram': {
    slug: 'onlyfans-ohne-instagram', category: 'Wachstum', eyebrow: 'Alternative Reichweite',
    title: 'OnlyFans ohne Instagram aufbauen: welche Alternativen ein stabiler Funnel braucht',
    metaTitle: 'OnlyFans ohne Instagram: alternative Reichweiten-Strategien',
    metaDescription: 'OnlyFans ohne Instagram aufbauen: alternative Discovery-Kanäle, eigene Reichweitenquellen, Content-Recycling und Risiko-Streuung.',
    lead: 'Instagram kann ein Kanal sein, muss aber nicht das Zentrum deiner gesamten Akquise sein. Ein robuster Funnel verteilt Aufmerksamkeit auf mehrere Quellen und hält trotzdem eine klare Marke zusammen.',
    shortAnswer: 'Baue mindestens einen alternativen Discovery-Kanal auf und entwickle eine eigene Kontakt- oder Wiederkehrmöglichkeit, soweit das rechtlich und plattformseitig zulässig ist. Recycle Themen kanaltypisch, statt Inhalte nur zu kopieren. Ziel ist nicht maximale Plattformzahl, sondern weniger Abhängigkeit von einem einzigen Algorithmus.',
    readingTime: '8 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Vermeide Single-Channel-Abhängigkeit', paragraphs: ['Wenn fast alle neuen Kontakte über einen Kanal kommen, kann eine Algorithmusänderung, Einschränkung oder Accountsperre den gesamten Funnel treffen. Das ist ein Geschäftsrisiko.', 'Du brauchst deshalb nicht sofort fünf Plattformen. Ein zweiter funktionierender Discovery-Kanal plus saubere Backups und dokumentierte Inhalte kann bereits viel Resilienz schaffen.'] },
      { title: 'Wähle Alternativen nach Content-Stärke', paragraphs: ['Kurzvideo, textbasierte Communitys, längere Videos oder Suchmaschinen-Traffic funktionieren unterschiedlich. Wähle den Kanal, dessen Format du wirklich bedienen kannst und auf dem deine Zielgruppe vorkommt.', 'Ein Kanal mit kleinerer Reichweite kann wertvoller sein, wenn die Besucher besser zu deiner Positionierung passen. Deshalb solltest du nicht nur Views vergleichen, sondern auch Profilbesuche und nachgelagerte Handlungen.'] },
      { title: 'Recycle Ideen, nicht Dateien', paragraphs: ['Dasselbe Thema kann auf mehreren Kanälen funktionieren, aber die Verpackung sollte angepasst werden. Ein kurzer Clip, ein Thread und ein ausführlicher Guide können aus derselben Kernidee entstehen.', 'So reduzierst du Produktionsaufwand, ohne überall identische Posts auszuspielen. Gleichzeitig stärkst du thematische Wiedererkennung.'] },
      { title: 'Baue wiederkehrende Kontaktpunkte', paragraphs: ['Wenn es zu deinem Setup und den jeweiligen Regeln passt, solltest du Wege schaffen, über die Menschen dich wiederfinden: konsistente Namen, klare Profile, eine zentrale Website oder andere zulässige Kontaktpunkte.', 'Wichtig ist, dass du nicht versuchst, Plattformregeln zu umgehen. Prüfe aktuelle Richtlinien zu Links, Werbung und erlaubten Inhalten, bevor du einen Funnel fest aufsetzt.'] },
      { title: 'Messe Quellen getrennt', paragraphs: ['Nutze, soweit technisch möglich, getrennte Links oder Kampagnenkennzeichnungen. Nur so erkennst du, welcher Kanal tatsächlich qualifizierten Traffic bringt.', 'Wenn ein Kanal viel Reichweite, aber kaum Profilaktionen bringt, kann er trotzdem für Markenbekanntheit sinnvoll sein. Du solltest seine Rolle nur realistisch einordnen.'] },
    ],
    checklistTitle: 'Funnel ohne Instagram', checklist: ['Zweiten Discovery-Kanal ausgewählt', 'Format an den Kanal angepasst', 'Konsistente Markenmerkmale verwendet', 'Content-Recycling-Workflow festgelegt', 'Zentrale Zielseite oder klare Linkstruktur vorhanden', 'Plattformregeln geprüft', 'Traffic-Quellen getrennt gemessen', 'Backup-Plan für Accounts und Content vorhanden'],
    related: ['social-media-funnel', 'onlyfans-follower-gewinnen', 'creator-account-sicherheit'], serviceLinks: [{ href: '/de/onlyfans-management', label: 'Plattformübergreifendes Management', text: 'Wir planen Distribution so, dass dein Wachstum nicht unnötig von einem einzigen Kanal abhängt.' }],
  },
  'onlyfans-management-vs-selbst-machen': {
    slug: 'onlyfans-management-vs-selbst-machen', category: 'Management', eyebrow: 'Management oder selbst?',
    title: 'OnlyFans Management oder selbst machen? Eine nüchterne Entscheidungshilfe',
    metaTitle: 'OnlyFans Management vs. selbst machen: Entscheidungshilfe',
    metaDescription: 'OnlyFans selbst managen oder Agentur nutzen? Aufgaben, Zeitbedarf, Kontrolle, Kosten, Datenzugang und Entscheidungskriterien im Vergleich.',
    lead: 'Management ist nicht automatisch besser als selbst machen. Die richtige Entscheidung hängt davon ab, welche Aufgaben dich tatsächlich bremsen und ob eine Agentur dafür messbaren Mehrwert schafft.',
    shortAnswer: 'Mach es selbst, wenn du Strategie, Content, Distribution und Auswertung zuverlässig abdecken kannst und die Zeit dafür hast. Management lohnt sich eher, wenn klare Engpässe entstehen und die Agentur transparent Prozesse, Rollen, Datenzugang und Verantwortlichkeiten verbessert. Gib Kontrolle nicht nur ab, um Arbeit unsichtbar zu machen.',
    readingTime: '10 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Liste die tatsächlichen Aufgaben auf', paragraphs: ['Creator Management besteht aus mehreren Bereichen: Positionierung, Redaktionsplanung, Produktion, Distribution, Community, Reporting, Sicherheit und Organisation. Nicht jede Agentur übernimmt dasselbe.', 'Schreibe auf, welche Aufgaben du heute selbst machst und wie viel Zeit sie kosten. Erst dann kannst du beurteilen, ob externe Unterstützung tatsächlich einen Engpass löst.'] },
      { title: 'Kontrolle und Delegation sind kein Widerspruch', paragraphs: ['Professionelle Delegation bedeutet nicht, Passwörter und Entscheidungen vollständig abzugeben. Rollen, Freigaben und Zuständigkeiten sollten klar dokumentiert sein.', 'Du solltest jederzeit wissen, welche Zugänge existieren, wer was verändern darf, welche Daten ausgewertet werden und wie du bei einer Trennung wieder vollständig handlungsfähig bist.'] },
      { title: 'Rechne mit Opportunitätskosten', paragraphs: ['Selbst machen kostet nicht nur Geld, sondern Zeit. Wenn du zehn Stunden pro Woche mit Organisation verbringst und dadurch weniger produzieren kannst, hat das einen Preis. Umgekehrt kann eine teure Agentur ohne klaren Mehrwert ebenfalls unwirtschaftlich sein.', 'Vergleiche deshalb nicht nur die Agenturgebühr mit null Euro. Vergleiche sie mit deiner eigenen Zeit, verlorener Produktionskapazität und der Qualität der Prozesse, die du selbst aufbauen müsstest.'] },
      { title: 'Transparenz ist ein Auswahlkriterium', paragraphs: ['Ein gutes Management sollte erklären können, welche Maßnahmen durchgeführt werden, welche Kennzahlen relevant sind und wie Entscheidungen entstehen. Reine Versprechen ohne nachvollziehbaren Prozess sind kein gutes Signal.', 'Lass dir außerdem erklären, welche Leistungen ausdrücklich nicht enthalten sind. Ein klarer Scope ist besser als ein vages „wir machen alles“.'] },
      { title: 'Nutze einen Entscheidungstest', paragraphs: ['Frage dich: Habe ich ein Wissensproblem, ein Zeitproblem oder ein Umsetzungsproblem? Bei einem Wissensproblem kann Beratung reichen. Bei einem Zeitproblem kann operative Unterstützung sinnvoll sein. Bei einem Umsetzungsproblem brauchst du möglicherweise Struktur und Verantwortlichkeit.', 'Die beste Lösung kann auch hybrid sein: Strategie und Reporting extern, Content und Community intern. Entscheidend ist, dass Rollen zu deinen Stärken passen.'], bullets: ['Welche Aufgabe ist heute der größte Engpass?', 'Welche Entscheidungen willst du niemals delegieren?', 'Welche Daten und Zugänge müssen bei dir bleiben?', 'Wie wird Erfolg konkret bewertet?'] },
    ],
    checklistTitle: 'Management-Entscheidung', checklist: ['Eigene Aufgaben und Zeitaufwand erfasst', 'Größten Engpass benannt', 'Nicht delegierbare Entscheidungen festgelegt', 'Agentur-Scope schriftlich verstanden', 'Zugriffs- und Rollenmodell geklärt', 'Reporting und Kennzahlen geklärt', 'Exit und Datenrückgabe verstanden', 'Kosten gegen eigenen Zeitaufwand verglichen'],
    related: ['creator-management-agentur', 'creator-agentur-vertrag-checkliste', 'creator-kennzahlen'], serviceLinks: [{ href: '/de/onlyfans-management', label: 'So arbeitet Prom4Fans im Management', text: 'Unsere Leistungsseite zeigt, welche Aufgaben wir verbinden und welche Kontrolle bei dir bleibt.' }],
  },
  'creator-agentur-vertrag-checkliste': {
    slug: 'creator-agentur-vertrag-checkliste', category: 'Management', eyebrow: 'Agentur auswählen',
    title: 'Creator-Agentur Vertrag prüfen: die wichtigsten Fragen vor einer Zusammenarbeit',
    metaTitle: 'Creator-Agentur Vertrag: Checkliste vor der Zusammenarbeit',
    metaDescription: 'Creator-Agentur-Vertrag prüfen: Leistungsumfang, Vergütung, Laufzeit, Zugänge, Daten, Inhalte, Kündigung und Reporting vorab klären.',
    lead: 'Ein Agenturvertrag sollte nicht nur sagen, was die Agentur bekommt. Er sollte verständlich regeln, wer welche Aufgaben übernimmt, welche Rechte benötigt werden und wie eine Zusammenarbeit wieder sauber endet.',
    shortAnswer: 'Prüfe insbesondere Leistungsumfang, Vergütung, Laufzeit, Kündigung, Zugänge, Nutzungsrechte, Datenzugriff und Reporting. Unklare Begriffe sollten vor der Unterschrift konkretisiert werden. Bei rechtlich wichtigen oder ungewöhnlichen Klauseln ist individuelle anwaltliche Beratung sinnvoll.',
    readingTime: '10 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Leistungsumfang muss konkret sein', paragraphs: ['Begriffe wie „Management“, „Marketing“ oder „Wachstum“ sind zu breit. Im Vertrag oder einer Leistungsbeschreibung sollte erkennbar sein, welche Aufgaben tatsächlich übernommen werden und in welcher Frequenz.', 'Frage auch nach Freigaben: Darf die Agentur selbst veröffentlichen, Preise ändern oder Nachrichten versenden? Welche Entscheidungen benötigen deine Zustimmung? Diese Punkte gehören in den operativen Alltag, nicht nur in ein Verkaufsgespräch.'] },
      { title: 'Vergütung vollständig verstehen', paragraphs: ['Kläre, ob die Vergütung fix, prozentual oder kombiniert ist und auf welche Umsätze sich eine Beteiligung bezieht. Relevant sind außerdem mögliche Zusatzkosten für Tools, Werbung, Produktion oder externe Dienstleister.', 'Lass dir anhand eines einfachen Rechenbeispiels zeigen, wie abgerechnet würde. Das ersetzt keine rechtliche oder steuerliche Beratung, macht aber Missverständnisse sichtbar.'] },
      { title: 'Laufzeit und Kündigung müssen praktisch funktionieren', paragraphs: ['Eine Kündigungsfrist ist nur ein Teil der Frage. Wichtig ist auch, was danach passiert: Wann enden Zugänge? Wer exportiert Daten? Was geschieht mit vorbereiteten Inhalten, Accounts, Domains oder Tracking-Setups?', 'Je stärker deine Infrastruktur von der Agentur abhängt, desto wichtiger wird ein sauberer Exit-Prozess. Idealerweise bleiben zentrale Accounts und Eigentumspositionen von Anfang an bei dir.'] },
      { title: 'Zugänge und Nutzungsrechte trennen', paragraphs: ['Ein Login-Zugang ist etwas anderes als ein Nutzungsrecht an Content. Kläre, wer welche Accounts verwaltet und welche Rechte die Agentur an Bildern, Videos, Texten oder Markenbestandteilen erhält.', 'Bei weitreichenden, exklusiven oder langfristigen Rechteklauseln solltest du genau verstehen, was sie bedeuten. Wenn du unsicher bist, lass solche Klauseln professionell prüfen.'] },
      { title: 'Reporting und Datenzugang festlegen', paragraphs: ['Du solltest auch während der Zusammenarbeit Zugang zu relevanten Leistungsdaten haben. Ein monatlicher Screenshot ohne Rohdaten oder Kontext erschwert die eigene Bewertung.', 'Vereinbare, welche Kennzahlen regelmäßig berichtet werden und wie Entscheidungen dokumentiert werden. Transparenz ist nicht nur angenehm, sondern schützt deine Handlungsfähigkeit.'], callout: 'Dieser Ratgeber ist eine praktische Prüfliste und keine Rechtsberatung. Bei Verträgen mit erheblichen finanziellen oder rechtlichen Folgen sollte eine qualifizierte Rechtsberatung hinzugezogen werden.' },
    ],
    checklistTitle: 'Vor der Unterschrift klären', checklist: ['Leistungsumfang konkret beschrieben', 'Freigabe- und Entscheidungsrechte geklärt', 'Vergütungsbasis vollständig verstanden', 'Zusatzkosten geprüft', 'Laufzeit und Kündigung verstanden', 'Exit-Prozess geklärt', 'Account-Eigentum und Zugänge geklärt', 'Nutzungsrechte an Content verstanden', 'Reporting und Datenzugang festgelegt', 'Unklare Rechtsklauseln professionell prüfen lassen'],
    related: ['creator-management-agentur', 'onlyfans-management-vs-selbst-machen', 'creator-account-sicherheit'], serviceLinks: [{ href: '/de/creator-management', label: 'Prom4Fans Creator Management', text: 'Auf unserer Leistungsseite beschreiben wir Scope, Zusammenarbeit und Kontrolle transparent, bevor es um eine Anfrage geht.' }],
  },
  'creator-nische-finden': {
    slug: 'creator-nische-finden', category: 'Einstieg', eyebrow: 'Nische finden',
    title: 'Als Creator eine Nische finden, ohne dich künstlich klein zu machen',
    metaTitle: 'Creator Nische finden: Positionierung ohne Schublade',
    metaDescription: 'Creator-Nische finden: Zielgruppe, Perspektive, Themen-Säulen und Wiedererkennung verbinden, ohne die eigene Persönlichkeit auf ein Keyword zu reduzieren.',
    lead: 'Eine Nische ist keine Schublade, in der du für immer bleiben musst. Sie ist ein klarer Einstiegspunkt, der neuen Menschen hilft zu verstehen, warum sie gerade dir folgen sollten.',
    shortAnswer: 'Suche nicht nach der kleinsten möglichen Zielgruppe, sondern nach der Schnittmenge aus deinen Stärken, wiederholbaren Themen und einer erkennbaren Nachfrage. Formuliere eine klare Perspektive und teste sie über mehrere Wochen. Gute Positionierung schafft Wiedererkennung, ohne deine Persönlichkeit zu verkleinern.',
    readingTime: '8 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Beginne bei wiederholbaren Stärken', paragraphs: ['Was kannst du über Monate glaubwürdig zeigen oder erzählen? Das kann Stil, Humor, Lebenserfahrung, Fitness, Alltag, bestimmte Interessen oder eine besondere Perspektive sein.', 'Eine Nische, die nur auf einem Trend basiert, wird schnell anstrengend. Suche deshalb nach Themen, zu denen du regelmäßig neue Beispiele und Geschichten beitragen kannst.'] },
      { title: 'Formuliere eine Zielgruppe als Mensch', paragraphs: ['Beschreibe nicht nur Alter und Geschlecht. Welche Situation hat die Person? Was findet sie unterhaltsam, inspirierend oder attraktiv? Warum würde sie wiederkommen?', 'Je konkreter du diese Person verstehst, desto leichter werden Themenwahl, Sprache und Plattformentscheidungen. Das ist hilfreicher als eine abstrakte Persona mit zwanzig demografischen Feldern.'] },
      { title: 'Kombiniere Thema und Perspektive', paragraphs: ['Viele Themen sind nicht einzigartig. Unterscheidung entsteht oft aus der Perspektive. Zwei Creator können dasselbe Thema behandeln und trotzdem völlig anders wirken.', 'Frage deshalb nicht nur „Worüber poste ich?“, sondern „Wie sehe ich dieses Thema anders als andere?“ Genau dort entstehen Stimme und Wiedererkennung.'] },
      { title: 'Teste mit Themen-Säulen', paragraphs: ['Lege drei bis fünf Säulen fest und veröffentliche mehrere Wochen konsistent. Danach kannst du sehen, welche Säule nicht nur Reichweite, sondern auch Profilbesuche, Antworten oder wiederkehrende Zuschauer erzeugt.', 'Entferne nicht sofort alles, was einmal schwach performt. Suche Muster über mehrere Inhalte und unterschiedliche Formate.'] },
      { title: 'Positionierung darf sich entwickeln', paragraphs: ['Wenn du merkst, dass ein Bereich besonders gut zu dir und deiner Community passt, darf der Fokus enger werden. Ebenso darfst du später erweitern.', 'Eine klare Startposition ist kein lebenslanger Vertrag. Sie gibt dir nur genug Richtung, um überhaupt belastbare Daten und Wiedererkennung aufzubauen.'] },
    ],
    checklistTitle: 'Nischen-Check', checklist: ['Eigene wiederholbare Stärken gesammelt', 'Zielgruppe als konkrete Person beschrieben', 'Drei bis fünf Themen-Säulen festgelegt', 'Eigene Perspektive pro Säule formuliert', 'Testzeitraum geplant', 'Nicht nur Reichweite als Signal definiert', 'Ergebnisse nach mehreren Wochen ausgewertet'],
    related: ['creator-positionierung', 'creator-35-plus', 'content-ideen-fuer-creator'], serviceLinks: [{ href: '/de/creator-management', label: 'Positionierung im Creator Management', text: 'Wir entwickeln Zielgruppe, Themen-Säulen und visuelle Richtung gemeinsam, statt eine fertige Schablone über dein Profil zu legen.' }],
  },
  'creator-hooks-schreiben': {
    slug: 'creator-hooks-schreiben', category: 'Content', eyebrow: 'Hooks schreiben',
    title: 'Hooks für Creator schreiben: Aufmerksamkeit gewinnen, ohne Clickbait zu werden',
    metaTitle: 'Hooks schreiben für Creator: Formeln, Beispiele & System',
    metaDescription: 'Hooks für Creator schreiben: Neugier, Kontrast, konkrete Ergebnisse und Story-Einstiege nutzen, ohne Erwartungen zu enttäuschen.',
    lead: 'Ein Hook soll nicht alles erzählen. Er soll der richtigen Person einen guten Grund geben, die nächsten Sekunden oder Zeilen zu bleiben.',
    shortAnswer: 'Gute Hooks kombinieren Relevanz und offene Information. Starte mit einem konkreten Problem, Kontrast, überraschenden Detail oder einer klaren Perspektive. Der restliche Content muss das Versprechen des Einstiegs anschließend wirklich einlösen – sonst steigt kurzfristig die Aufmerksamkeit, aber langfristig sinkt Vertrauen.',
    readingTime: '8 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Relevanz kommt vor Kreativität', paragraphs: ['Ein kunstvoller Satz hilft wenig, wenn die Zielgruppe nicht erkennt, warum sie zuhören sollte. Beginne mit einem Problem, Wunsch, Konflikt oder Detail, das für genau diese Menschen Bedeutung hat.', 'Die stärkste Formulierung entsteht oft erst nach dem Inhalt. Schreibe den Post oder das Video grob fertig und formuliere danach mehrere mögliche Einstiege.'] },
      { title: 'Vier Hook-Arten reichen für den Anfang', paragraphs: ['Du brauchst keine Liste mit hundert Formeln. Vier Muster decken sehr viel ab: Problem, Kontrast, konkrete Beobachtung und offene Geschichte.', 'Beispiele wären: „Der Fehler war nicht zu wenig Content …“, „Ich dachte lange X – bis Y passiert ist“, „Drei Dinge, die ich heute anders machen würde“ oder „Diese eine Zahl hat unseren Plan verändert“.'], bullets: ['Problem: ein konkreter Schmerzpunkt', 'Kontrast: Erwartung gegen Realität', 'Beobachtung: ein spezifisches Detail', 'Story: eine offene Entwicklung'] },
      { title: 'Vermeide falsche Neugier', paragraphs: ['Clickbait entsteht, wenn der Einstieg mehr verspricht als der Inhalt liefert. Kurzfristig kann das Views erhöhen, langfristig aber Vertrauen und Retention beschädigen.', 'Prüfe daher jeden Hook mit einer einfachen Frage: Würde eine Person nach dem Content sagen, dass die angekündigte Frage wirklich beantwortet wurde?'] },
      { title: 'Passe den Hook an den Kanal an', paragraphs: ['In Kurzvideo muss der Einstieg sofort funktionieren. In längeren Texten darf er etwas mehr Kontext enthalten. Auf einer Profilseite kann die erste Zeile stärker auf Positionierung einzahlen.', 'Das Kernthema kann gleich bleiben, aber Länge und Mechanik des Einstiegs sollten zum Nutzungsmoment passen.'] },
      { title: 'Baue eine eigene Hook-Bibliothek', paragraphs: ['Speichere nicht nur fremde Beispiele, sondern vor allem deine eigenen funktionierenden Einstiege. Notiere Thema, Hook, Format und Ergebnis.', 'Nach einigen Wochen entstehen Muster, die zu deiner Stimme passen. Daraus kannst du Vorlagen ableiten, ohne dass deine Texte wie Copy-Paste wirken.'] },
    ],
    checklistTitle: 'Hook vor Veröffentlichung prüfen', checklist: ['Zielgruppe erkennt sofort die Relevanz', 'Hook enthält ein konkretes Detail', 'Nicht die komplette Antwort vorweggenommen', 'Versprechen wird im Content eingelöst', 'Sprache passt zur eigenen Stimme', 'Hook an den Kanal angepasst', 'Mehrere Varianten geschrieben', 'Ergebnis später dokumentiert'],
    related: ['content-ideen-fuer-creator', 'content-plan-erstellen', 'social-media-funnel'], serviceLinks: [{ href: '/de/creator-management', label: 'Content-System & Distribution', text: 'Hooks sind ein Baustein. Wir verbinden sie mit Formaten, Themen-Säulen und dem restlichen Funnel.' }],
  },
};

export const extraGuideList = Object.values(extraGuides);
