import type { ExtraGuidePage } from '@/lib/extra-guide-pages';

export const pillarGuides: Record<string, ExtraGuidePage> = {
  'onlyfans-guide': {
    slug: 'onlyfans-guide',
    category: 'Einstieg',
    eyebrow: 'OnlyFans Guide',
    title: 'Der große OnlyFans Guide: von Positionierung bis Wachstum als zusammenhängendes System',
    metaTitle: 'OnlyFans Guide: Start, Content, Marketing & Management',
    metaDescription: 'Der zentrale OnlyFans Guide für Creator: Positionierung, Profil, Content, Preise, Reichweite, Sicherheit, Kennzahlen und Management sinnvoll verbinden.',
    lead: 'Viele Einzel-Tipps widersprechen sich, weil sie nur einen Teil des Systems betrachten. Dieser Guide ordnet die wichtigsten Entscheidungen in eine sinnvolle Reihenfolge und zeigt, welche Themen zuerst geklärt werden sollten.',
    shortAnswer: 'Baue zuerst Positionierung, Grenzen und Profil auf. Danach folgen ein belastbares Content-System, ein klarer Preis- und Angebotsrahmen, Reichweitenkanäle außerhalb der Subscription-Plattform und ein einfaches Reporting. Optimiere nicht alles gleichzeitig: Erst wenn du weißt, an welcher Stelle des Funnels Menschen abspringen, lohnt sich eine gezielte Änderung.',
    readingTime: '14 Min.',
    published: '2026-09-06',
    updated: '2026-09-06',
    sections: [
      {
        title: '1. Positionierung ist die Grundlage für jede spätere Entscheidung',
        paragraphs: [
          'Bevor du Profiltexte, Preise oder Posting-Frequenzen festlegst, solltest du wissen, wofür dein Auftritt steht. Eine gute Positionierung beschreibt nicht nur Alter, Aussehen oder Thema, sondern die Kombination aus Zielgruppe, Persönlichkeit, visueller Linie, Tonalität und persönlichen Grenzen.',
          'Je klarer diese Grundlage ist, desto leichter werden spätere Entscheidungen. Ein Profil mit ruhiger, hochwertiger Inszenierung braucht andere Formate als ein sehr spontaner, humorvoller Account. Beides kann funktionieren. Problematisch wird es erst, wenn Profil, Content und Vermarktung unterschiedliche Erwartungen erzeugen.',
        ],
        bullets: ['Zielgruppe in einem Satz beschreiben', 'Drei bis fünf wiederkehrende Themen definieren', 'Tonalität und visuelle Linie festlegen', 'Persönliche Grenzen schriftlich notieren'],
      },
      {
        title: '2. Das Profil muss in wenigen Sekunden verständlich sein',
        paragraphs: [
          'Profilbild, Name, Bio und sichtbare Inhalte sollten dieselbe Geschichte erzählen. Eine neue Person muss schnell verstehen, wer du bist, welche Art von Content sie erwartet und warum dein Profil anders ist als hunderte ähnliche Accounts.',
          'Vermeide austauschbare Aussagen ohne Kontext. Eine klare Bio, ein wiedererkennbarer Stil und ein nachvollziehbarer Veröffentlichungsrhythmus schaffen mehr Orientierung als möglichst viele Superlative. Änderungen sollten einzeln getestet werden, damit du ihre Wirkung später überhaupt beurteilen kannst.',
        ],
      },
      {
        title: '3. Content braucht ein Produktionssystem statt täglicher Improvisation',
        paragraphs: [
          'Nach dem Profil ist der größte Hebel ein System, das auch in stressigen Wochen funktioniert. Arbeite mit Themen-Säulen, wiederkehrenden Serien und einem Backlog. Plane Inhalte in Blöcken und produziere mehrere Formate in einer Session, wenn das zu deinem Alltag passt.',
          'Ein gutes Content-System trennt Ideenfindung, Produktion, Veröffentlichung und Auswertung. Dadurch musst du nicht jeden Tag alle Entscheidungen neu treffen. Gleichzeitig entsteht ein Puffer, der dir erlaubt, Qualität zu halten, ohne ständig verfügbar sein zu müssen.',
        ],
        callout: 'Ein System ist besser als maximale Frequenz, wenn du es über Monate zuverlässig durchhalten kannst.',
      },
      {
        title: '4. Marketing beginnt außerhalb der Subscription-Plattform',
        paragraphs: [
          'Ein gutes Profil erzeugt keinen Traffic von allein. Du brauchst mindestens einen Kanal, auf dem neue Menschen dich entdecken können. Der Weg sollte von Aufmerksamkeit über Interesse und Vertrauen zu einem klaren nächsten Schritt führen.',
          'Miss deshalb nicht nur Follower. Wichtiger ist, ob aus Reichweite Profilbesuche entstehen, ob Menschen wiederkommen und ob sie schließlich die gewünschte Handlung ausführen. Wenn viele Menschen den oberen Teil des Funnels sehen, aber kaum jemand weitergeht, liegt das Problem häufig in Positionierung, Profil oder Erwartungsmanagement.',
        ],
      },
      {
        title: '5. Preis, Retention und Kennzahlen gehören zusammen',
        paragraphs: [
          'Der Preis sollte zum Leistungsumfang und zur Zielgruppe passen. Bewerte nicht nur Erstabschlüsse, sondern auch Verlängerungen und den Wert eines gewonnenen Subscribers über mehrere Monate. Ein niedriger Einstiegspreis ist nicht automatisch besser, wenn die Bindung schwach bleibt.',
          'Nutze wenige Kennzahlen, die den Funnel abbilden: Reichweite, Profilbesuche, Klicks beziehungsweise Übergänge, Conversion und Retention. So erkennst du eher, welches Glied tatsächlich schwach ist und vermeidest hektische Änderungen an mehreren Stellen gleichzeitig.',
        ],
      },
      {
        title: '6. Management lohnt sich erst, wenn der Engpass klar ist',
        paragraphs: [
          'Eine Agentur oder ein Management kann Strategie, Planung, Reporting und operative Abläufe übernehmen. Das ist aber nur sinnvoll, wenn Rollen, Zugänge, Entscheidungsrechte, Vergütung und Kündigung sauber geregelt sind.',
          'Wenn du selbst noch nicht weißt, was du auslagern möchtest, wird auch ein externer Partner schwer messbar. Definiere deshalb zuerst, welche Aufgaben dich bremsen und welche Entscheidungen bei dir bleiben müssen. Danach lässt sich viel besser beurteilen, ob Unterstützung tatsächlich Mehrwert bringt.',
        ],
      },
    ],
    checklistTitle: 'OnlyFans-System in der richtigen Reihenfolge',
    checklist: ['Positionierung und Zielgruppe festgelegt', 'Persönliche Grenzen dokumentiert', 'Profil klar und konsistent aufgebaut', 'Content-Säulen und Serien definiert', 'Produktionspuffer eingerichtet', 'Mindestens einen Discovery-Kanal priorisiert', 'Funnel-Kennzahlen festgelegt', 'Preis und Retention gemeinsam bewertet', 'Management nur bei klarem Engpass geprüft'],
    related: ['onlyfans-starten', 'onlyfans-profil-optimieren', 'onlyfans-bio-schreiben', 'onlyfans-preise-festlegen', 'onlyfans-follower-gewinnen', 'social-media-funnel', 'onlyfans-anonym-starten', 'creator-account-sicherheit', 'onlyfans-management-vs-selbst-machen'],
    serviceLinks: [
      { href: '/de/onlyfans-management', label: 'OnlyFans Management', text: 'Wenn du Strategie, Content, Distribution und Reporting nicht selbst zusammensetzen möchtest, zeigen wir dir, wie diese Bausteine im Management verbunden werden.' },
      { href: '/de/creator-management', label: 'Creator Management', text: 'Für Creator, die ihre gesamte Positionierung und Content-Struktur professionell organisieren wollen.' },
    ],
  },

  'onlyfans-marketing': {
    slug: 'onlyfans-marketing',
    category: 'Wachstum',
    eyebrow: 'OnlyFans Marketing',
    title: 'OnlyFans Marketing: Reichweite, Vertrauen und Conversion als einen Funnel denken',
    metaTitle: 'OnlyFans Marketing: Strategie für Reichweite & Conversion',
    metaDescription: 'OnlyFans Marketing systematisch aufbauen: Positionierung, Social Funnel, Content, Profil, Conversion, Retention und Kennzahlen sinnvoll verbinden.',
    lead: 'Marketing ist nicht das möglichst aggressive Bewerben eines Links. Es ist ein System, das neue Menschen erreicht, Interesse aufbaut, Vertrauen schafft und ihnen einen nachvollziehbaren nächsten Schritt gibt.',
    shortAnswer: 'Wähle ein bis zwei Discovery-Kanäle, entwickle wiedererkennbare Content-Formate und führe Interessenten auf ein Profil, das die Erwartung klar fortsetzt. Miss Reichweite, Profilbesuche, Klicks, Conversion und Retention getrennt. So erkennst du, ob du mehr Traffic brauchst oder ob vorhandener Traffic nur schlecht weitergeführt wird.',
    readingTime: '11 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Marketing beginnt mit einer klaren Zielgruppe', paragraphs: ['Ohne Zielgruppe wird Reichweite schnell beliebig. Je genauer du weißt, welche Menschen deine Persönlichkeit, Themen und Ästhetik besonders interessant finden, desto leichter kannst du Inhalte auswählen, die genau diese Menschen anziehen.', 'Positionierung bedeutet nicht, jede andere Person auszuschließen. Sie hilft vielmehr dabei, dass die richtigen Menschen schneller erkennen, warum dein Profil für sie relevant ist. Diese Klarheit verbessert meist auch Bio, Hooks und Content-Auswahl.'] },
      { title: 'Baue Discovery, Vertrauen und Handlung als getrennte Stufen', paragraphs: ['Ein kurzer Discovery-Post hat eine andere Aufgabe als ein persönlicher Story-Post oder eine Profilseite. Der erste soll Aufmerksamkeit verdienen, der zweite Beziehung aufbauen und das Profil schließlich Orientierung für die nächste Handlung geben.', 'Wenn jeder Post sofort verkaufen soll, wirkt der Funnel häufig zu abrupt. Wenn du dagegen nur Reichweite aufbaust, aber nie einen klaren nächsten Schritt anbietest, bleibt Aufmerksamkeit ungenutzt. Ein gutes System braucht alle drei Stufen.'], bullets: ['Discovery: neue Menschen erreichen', 'Trust: Wiedererkennung und Beziehung aufbauen', 'Intent: Interesse konkretisieren', 'Conversion: nächsten Schritt klar machen'] },
      { title: 'Ein Hauptkanal ist besser als fünf halb gepflegte Profile', paragraphs: ['Wähle zunächst den Kanal, auf dem du deine Zielgruppe am zuverlässigsten erreichst und dessen Format du langfristig produzieren kannst. Erst wenn dort ein stabiler Rhythmus funktioniert, lohnt sich eine zweite Plattform.', 'Crossposting kann sinnvoll sein, aber nicht jede Plattform belohnt dieselbe Aufbereitung. Passe Hook, Länge und Verpackung an den jeweiligen Kanal an, während die zentrale Positionierung gleich bleibt.'] },
      { title: 'Optimiere den Engpass statt die lauteste Kennzahl', paragraphs: ['Viele Creator schauen zuerst auf Follower. Für Entscheidungen ist jedoch wichtiger, wie Menschen durch den gesamten Funnel gehen. Große Reichweite mit wenigen Profilbesuchen weist auf ein anderes Problem hin als viele Profilbesuche mit kaum Conversions.', 'Dokumentiere deshalb den Weg von Reichweite über Profilbesuch und Klick bis zur Subscription beziehungsweise zur gewünschten Handlung. So kannst du gezielt testen, statt gleichzeitig Profil, Preis und Content zu verändern.'] },
      { title: 'Retention ist Teil des Marketings', paragraphs: ['Marketing endet nicht beim ersten Abschluss. Wenn neue Subscriber schnell wieder gehen, ist das ein Signal dafür, dass Erwartung und tatsächliches Erlebnis nicht gut genug zusammenpassen.', 'Nutze Feedback, Content-Nutzung und Verlängerungen, um zu prüfen, ob das Marketing die richtigen Erwartungen setzt. Langfristig ist eine kleinere, passende Zielgruppe oft wertvoller als große Mengen unpassenden Traffics.'], callout: 'Der beste Funnel bringt nicht einfach mehr Menschen hinein, sondern die richtigen Menschen bis zur passenden nächsten Handlung.' },
    ],
    checklistTitle: 'Marketing-Funnel aufsetzen', checklist: ['Zielgruppe beschrieben', 'Ein Haupt-Discovery-Kanal gewählt', 'Drei wiederkehrende Discovery-Formate definiert', 'Vertrauens-Content eingeplant', 'Profil als klare Zielseite optimiert', 'Call-to-Action verständlich', 'Funnel-Kennzahlen dokumentiert', 'Retention als Qualitätskennzahl aufgenommen'],
    related: ['social-media-funnel', 'onlyfans-follower-gewinnen', 'onlyfans-ohne-instagram', 'creator-positionierung', 'creator-kennzahlen', 'onlyfans-profil-optimieren'],
    serviceLinks: [{ href: '/de/onlyfans-management', label: 'OnlyFans Management', text: 'Wir verbinden Positionierung, Content, Distribution und Auswertung zu einem messbaren Marketing-System.' }],
  },

  'creator-marketing': {
    slug: 'creator-marketing',
    category: 'Wachstum',
    eyebrow: 'Creator Marketing',
    title: 'Creator Marketing: eine Marke aufbauen, die nicht von einem einzigen Kanal abhängt',
    metaTitle: 'Creator Marketing: Marke, Content & Funnel aufbauen',
    metaDescription: 'Creator Marketing nachhaltig planen: Positionierung, Content-Säulen, Distribution, Community, Conversion und kanalübergreifende Markenführung.',
    lead: 'Creator Marketing wird stabiler, wenn deine Marke größer ist als ein einzelner Algorithmus. Ziel ist eine wiedererkennbare Positionierung, die sich auf mehrere Formate und Kanäle übertragen lässt.',
    shortAnswer: 'Definiere zuerst deine Marke und Themen-Säulen. Nutze einen Hauptkanal für Discovery, einen klaren Ort für vertiefte Beziehung und eine eindeutige Conversion-Strecke. Sammle eigene Learnings aus Daten und Community-Reaktionen, damit du nicht bei jedem Algorithmuswechsel deine gesamte Strategie neu erfinden musst.',
    readingTime: '10 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Die Marke muss vor dem Kanal stehen', paragraphs: ['Wenn deine Identität vollständig an ein einzelnes Format oder einen Trend gebunden ist, wird jede Plattformänderung zum strategischen Problem. Eine belastbare Creator-Marke besteht aus wiederkehrenden Themen, einer klaren Perspektive, Tonalität und visuellen Merkmalen.', 'Diese Elemente können über Plattformen hinweg gleich bleiben, auch wenn Formate unterschiedlich sind. Dadurch erkennt die Community dich wieder, ohne dass du überall exakt denselben Content veröffentlichen musst.'] },
      { title: 'Content-Säulen geben der Marke Struktur', paragraphs: ['Wähle wenige Themen, in denen du dauerhaft etwas erzählen kannst. Sie helfen beim Ideenfinden und verhindern, dass ein Account beliebig wirkt. Innerhalb dieser Säulen kannst du unterschiedliche Formate und Perspektiven testen.', 'Eine gute Säule ist breit genug für viele Beiträge und spezifisch genug, dass sie zu deiner Positionierung passt. Prüfe regelmäßig, welche Säulen tatsächlich Resonanz erzeugen und welche nur Aufwand verursachen.'] },
      { title: 'Distribution ist ein eigener Arbeitsschritt', paragraphs: ['Guter Content ohne Distribution wird oft unterschätzt. Plane bereits vor der Produktion, auf welchem Kanal ein Thema entdeckt werden soll und wo interessierte Menschen anschließend mehr bekommen.', 'Du kannst aus einer Kernidee mehrere Verpackungen machen: einen kurzen Hook für Discovery, eine persönliche Story für Vertrauen, einen längeren Guide für Tiefe und einen klaren CTA für den nächsten Schritt.'] },
      { title: 'Community ist kein Nebenprodukt', paragraphs: ['Kommentare, DMs, Antworten und wiederkehrende Fragen zeigen dir, welche Themen wirklich relevant sind. Sie helfen gleichzeitig bei Ideenfindung, Positionierung und Produktentwicklung.', 'Baue klare Kommunikationszeiten ein, statt permanente Erreichbarkeit zu versprechen. Verlässliche, begrenzte Interaktion ist häufig nachhaltiger als ständige Präsenz.'] },
      { title: 'Messung soll Entscheidungen vereinfachen', paragraphs: ['Beobachte wenige Kennzahlen entlang des Funnels und verbinde sie mit konkreten Hypothesen. Wenn Reichweite steigt, aber Profilbesuche nicht, sollte die nächste Frage anders lauten als bei vielen Profilbesuchen ohne Conversion.', 'Das Ziel ist kein perfektes Dashboard, sondern ein Entscheidungsrhythmus: Was funktioniert, was testen wir als Nächstes und was stoppen wir bewusst?'], callout: 'Eine stabile Creator-Marke erzeugt eigene Wiedererkennung – nicht nur geliehene Reichweite aus einem Algorithmus.' },
    ],
    checklistTitle: 'Creator-Marketing-Fundament', checklist: ['Markenkern in einem Satz formuliert', 'Drei bis fünf Themen-Säulen festgelegt', 'Hauptkanal für Discovery priorisiert', 'Vertrauensformat definiert', 'Conversion-Strecke festgelegt', 'Community-Signale systematisch gesammelt', 'Kernkennzahlen dokumentiert', 'Monatlichen Review-Termin eingeplant'],
    related: ['creator-positionierung', 'content-ideen-fuer-creator', 'redaktionsplan-fuer-creator', 'social-media-funnel', 'creator-kennzahlen', 'creator-nische-finden'],
    serviceLinks: [{ href: '/de/creator-management', label: 'Creator Management', text: 'Wir bauen Positionierung, Content-System, Distribution und Reporting als zusammenhängende Creator-Marke auf.' }],
  },

  'onlyfans-agentur-kosten': {
    slug: 'onlyfans-agentur-kosten',
    category: 'Management',
    eyebrow: 'Agentur Kosten',
    title: 'Was kostet eine OnlyFans Agentur? So vergleichst du Vergütung, Leistung und tatsächlichen Gegenwert',
    metaTitle: 'OnlyFans Agentur Kosten: Modelle & Vergleich',
    metaDescription: 'OnlyFans Agentur Kosten richtig vergleichen: Umsatzbeteiligung, Fixpreis, Leistungsumfang, Zusatzkosten, Vertragslaufzeit und tatsächlichen Gegenwert bewerten.',
    lead: 'Eine Prozentzahl allein sagt fast nichts über den Preis einer Agentur aus. Entscheidend ist, welche Aufgaben tatsächlich übernommen werden, welche Kosten zusätzlich entstehen und wie viel Kontrolle du behältst.',
    shortAnswer: 'Vergleiche Agenturen nicht nur nach Umsatzbeteiligung oder Monatsgebühr. Stelle den vollständigen Leistungsumfang, Zusatzkosten, Vertragslaufzeit, Kündigungsregeln, Account-Zugänge und Reporting gegenüber. Ein höherer Preis kann sinnvoll sein, wenn wirklich relevante Arbeit übernommen wird; ein niedriger Preis ist teuer, wenn Leistung unklar bleibt oder du Kontrolle verlierst.',
    readingTime: '10 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Die häufigsten Vergütungsmodelle', paragraphs: ['Agenturen können mit prozentualer Umsatzbeteiligung, Fixpreis oder Mischmodellen arbeiten. Keines dieser Modelle ist automatisch fair oder unfair. Entscheidend ist, welche Leistung dahintersteht und wie transparent die Berechnung ist.', 'Bei einer Umsatzbeteiligung solltest du klären, auf welche Umsätze sich die Prozentzahl bezieht, welche Gebühren vorher oder nachher abgezogen werden und wie Rückerstattungen behandelt werden. Bei Fixpreisen ist wichtig, welche Leistungen tatsächlich enthalten sind.'], bullets: ['Umsatzbeteiligung', 'Feste Monatsgebühr', 'Mischmodell aus Fixum und Beteiligung', 'Projekt- oder Setup-Gebühren'] },
      { title: 'Leistungsumfang macht den Preis vergleichbar', paragraphs: ['Zwei Agenturen mit derselben Prozentzahl können wirtschaftlich völlig unterschiedlich sein. Eine übernimmt vielleicht Strategie, Planung, Reporting und Distribution, während die andere nur einen Teilbereich betreut.', 'Lass dir deshalb Leistungen konkret beschreiben: Wer plant Content? Wer erstellt Auswertungen? Wer übernimmt Kommunikation? Wer verantwortet Sicherheit und Zugänge? Je klarer der Scope, desto besser kannst du den Preis einordnen.'] },
      { title: 'Achte auf versteckte operative Kosten', paragraphs: ['Zusätzliche Software, Werbebudget, externe Produktion, Foto- oder Videokosten und Freelancer können den tatsächlichen Preis deutlich verändern. Diese Kosten sollten vor Vertragsbeginn transparent sein.', 'Frage auch, welche Leistungen bei Wachstum teurer werden. Manche Modelle wirken am Anfang günstig und verändern sich später stark, wenn Umsatz oder Arbeitsvolumen steigt.'] },
      { title: 'Vertragslaufzeit und Exit haben einen wirtschaftlichen Wert', paragraphs: ['Ein günstiges Modell kann unattraktiv sein, wenn du lange gebunden bist oder Zugänge, Daten und Arbeitsstände beim Exit nicht sauber zurückbekommst. Kündigungsfrist, Account-Eigentum und Datenexport gehören deshalb in die Preisbewertung.', 'Rechne nicht nur die monatliche Gebühr, sondern die Kosten eines realistischen Vertragszeitraums. So vergleichst du Modelle auf derselben Grundlage.'] },
      { title: 'Bewerte den Gegenwert mit klaren Aufgaben und Kennzahlen', paragraphs: ['Eine Agentur sollte nicht nur mit allgemeinen Wachstumsversprechen bewertet werden. Prüfe, welche operative Zeit sie dir spart, welche Qualität sie verbessert und welche Entscheidungen durch Reporting besser werden.', 'Definiere vorab wenige Ziele: Content-Rhythmus, Prozessqualität, Funnel-Kennzahlen, Response-Zeiten oder andere messbare Ergebnisse. So kannst du nach einigen Wochen nüchterner beurteilen, ob die Zusammenarbeit ihren Preis wert ist.'], callout: 'Der teuerste Vertrag ist nicht automatisch der mit dem höchsten Prozentsatz, sondern der mit unklarem Scope, schwacher Transparenz und schlechtem Exit.' },
    ],
    checklistTitle: 'Kostenvergleich vor Vertragsabschluss', checklist: ['Vergütungsmodell vollständig verstanden', 'Berechnungsbasis schriftlich geklärt', 'Leistungsumfang konkret aufgelistet', 'Zusatzkosten und Werbebudget getrennt ausgewiesen', 'Laufzeit und Kündigungsfrist geprüft', 'Account- und Datenhoheit geregelt', 'Reporting-Frequenz vereinbart', 'Gesamtkosten über die Vertragsdauer verglichen'],
    related: ['creator-management-agentur', 'creator-agentur-vertrag-checkliste', 'onlyfans-management-vs-selbst-machen', 'creator-kennzahlen'],
    serviceLinks: [{ href: '/de/onlyfans-management', label: 'Prom4Fans Leistungsumfang ansehen', text: 'Vergleiche nicht nur Preise, sondern welche Aufgaben, Prozesse und Transparenz tatsächlich enthalten sind.' }],
  },

  'was-macht-eine-onlyfans-agentur': {
    slug: 'was-macht-eine-onlyfans-agentur',
    category: 'Management',
    eyebrow: 'OnlyFans Agentur',
    title: 'Was macht eine OnlyFans Agentur? Aufgaben, Grenzen und Verantwortlichkeiten verständlich erklärt',
    metaTitle: 'Was macht eine OnlyFans Agentur? Aufgaben & Ablauf',
    metaDescription: 'Was eine OnlyFans Agentur typischerweise übernimmt: Strategie, Positionierung, Content-Planung, Marketing, Reporting, Prozesse, Rollen und wichtige Grenzen.',
    lead: 'Der Begriff OnlyFans Agentur wird für sehr unterschiedliche Leistungen verwendet. Deshalb solltest du nicht vom Namen auf den tatsächlichen Scope schließen, sondern jede Aufgabe und Verantwortung einzeln betrachten.',
    shortAnswer: 'Eine gute Agentur kann Positionierung, Strategie, Content-Planung, Distribution, Reporting und operative Prozesse unterstützen. Welche Aufgaben tatsächlich übernommen werden, muss vertraglich klar sein. Persönliche Grenzen, Account-Hoheit, Freigaben und sensible Entscheidungen sollten transparent geregelt bleiben.',
    readingTime: '10 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Strategie und Positionierung', paragraphs: ['Am Anfang sollte eine Agentur verstehen, wofür der Creator stehen möchte, welche Zielgruppe angesprochen wird und welche persönlichen Grenzen gelten. Daraus entstehen Tonalität, visuelle Linie, Themen und eine sinnvolle Kanalstrategie.', 'Wenn diese Grundlagen fehlen, optimiert die Agentur später möglicherweise nur einzelne Kennzahlen, ohne dass ein konsistentes Markenbild entsteht. Strategie bedeutet deshalb mehr als ein Redaktionsplan.'] },
      { title: 'Content-Planung und Produktionssystem', paragraphs: ['Eine Agentur kann Themen-Säulen, Serien, Produktionsblöcke und Freigaben organisieren. Ziel sollte sein, den Alltag planbarer zu machen und nicht zusätzlichen Abstimmungsstress zu erzeugen.', 'Wichtig ist, wer tatsächlich produziert und wer nur plant. Foto- und Videoerstellung, Editing, Copywriting und Posting können unterschiedliche Verantwortlichkeiten sein. Diese Aufgaben sollten im Scope einzeln genannt werden.'] },
      { title: 'Marketing und Distribution', paragraphs: ['Zur Vermarktung gehören Discovery-Kanäle, Content-Verteilung, Funnel-Logik und die Auswertung von Übergängen zwischen Reichweite, Profil und Conversion. Eine Agentur sollte erklären können, welche Kanäle sie warum priorisiert.', 'Vorsicht bei pauschalen Versprechen ohne nachvollziehbare Methode. Gute Arbeit lässt sich besser an Prozessen, Tests und dokumentierten Learnings erkennen als an garantierten Umsatzzahlen.'] },
      { title: 'Reporting und operative Prozesse', paragraphs: ['Ein gutes Management schafft Transparenz: Welche Inhalte laufen, welche Hypothesen werden getestet, welche Aufgaben sind offen und was wird als Nächstes verändert? Dazu braucht es kein überladenes Dashboard, aber einen regelmäßigen Review.', 'Auch Zugänge, Passwort-Management, Rollen und Datensicherheit gehören in den operativen Prozess. Je mehr Personen Zugriff haben, desto wichtiger werden klare Berechtigungen und ein sauberer Exit-Prozess.'] },
      { title: 'Was eine Agentur nicht entscheiden sollte', paragraphs: ['Persönliche Grenzen, Identität, sensible Inhalte und zentrale Markenentscheidungen sollten nicht ohne eindeutige Freigabe übergangen werden. Delegation bedeutet nicht, die Kontrolle über das eigene Profil abzugeben.', 'Definiere deshalb ausdrücklich, welche Entscheidungen die Agentur selbst treffen darf, welche nur nach Freigabe erfolgen und welche grundsätzlich beim Creator bleiben.'], callout: 'Eine gute Agentur reduziert operative Last und erhöht Klarheit – sie ersetzt nicht deine Kontrolle über Identität, Grenzen und Accounts.' },
    ],
    checklistTitle: 'Scope einer Agentur prüfen', checklist: ['Strategie und Positionierung beschrieben', 'Content-Aufgaben einzeln benannt', 'Marketing-Kanäle und Verantwortlichkeiten klar', 'Reporting-Rhythmus festgelegt', 'Freigaben und Entscheidungsrechte definiert', 'Account-Zugänge geregelt', 'Persönliche Grenzen dokumentiert', 'Exit- und Übergabeprozess vereinbart'],
    related: ['onlyfans-agentur-kosten', 'creator-management-agentur', 'creator-agentur-vertrag-checkliste', 'onlyfans-management-vs-selbst-machen'],
    serviceLinks: [{ href: '/de/onlyfans-management', label: 'So arbeitet Prom4Fans', text: 'Auf der Leistungsseite siehst du, wie wir Strategie, Content, Prozesse und Reporting strukturieren.' }],
  },

  'fansly-vs-onlyfans': {
    slug: 'fansly-vs-onlyfans',
    category: 'Analyse',
    eyebrow: 'Fansly vs OnlyFans',
    title: 'Fansly vs OnlyFans: welche Plattform passt besser zu deinem Creator-System?',
    metaTitle: 'Fansly vs OnlyFans: Vergleich für Creator',
    metaDescription: 'Fansly vs OnlyFans vergleichen: Zielgruppe, Discovery, Content-Workflow, Monetarisierung, Richtlinien, Analytics und Plattformrisiko systematisch bewerten.',
    lead: 'Die bessere Plattform ist nicht automatisch die mit dem bekannteren Namen oder den meisten Funktionen. Entscheidend ist, wie gut sie zu deiner Zielgruppe, deinem Content-Workflow und deiner Vermarktungsstrategie passt.',
    shortAnswer: 'Vergleiche Fansly und OnlyFans anhand deiner eigenen Prioritäten: Wo befindet sich deine Zielgruppe, wie gewinnst du neue Besucher, welche Content- und Monetarisierungsfunktionen brauchst du, wie gut passt dein Workflow und wie hoch ist deine Abhängigkeit von einer einzelnen Plattform? Prüfe aktuelle Gebühren, Auszahlungsbedingungen und Richtlinien zusätzlich direkt bei den Plattformen, weil sich Details ändern können.',
    readingTime: '11 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Beginne mit deiner Zielgruppe statt mit Funktionen', paragraphs: ['Eine lange Feature-Liste hilft wenig, wenn deine relevante Zielgruppe auf einer Plattform kaum aktiv ist. Prüfe deshalb zuerst, wo bestehende Follower bereits Accounts haben und welche Plattform in deinen Discovery-Kanälen am leichtesten erklärt werden kann.', 'Markenbekanntheit kann Conversion erleichtern, während interne Discovery-Funktionen einer Alternative beim Aufbau neuer Reichweite helfen können. Welche Seite stärker wiegt, hängt von deinem vorhandenen Traffic ab.'] },
      { title: 'Vergleiche Discovery und externen Traffic getrennt', paragraphs: ['Ein Creator mit großer Social-Reichweite braucht weniger interne Discovery als jemand, der noch am Anfang steht. Betrachte deshalb zwei Fragen: Wie gut bringt die Plattform selbst neue Menschen zu dir und wie gut konvertiert dein externer Traffic dort?', 'Teste nicht nur Registrierungen oder Follower, sondern den gesamten Weg von Discovery über Profilbesuch bis zur Subscription. So erkennst du, ob eine Plattform tatsächlich besser zu deinem Funnel passt.'] },
      { title: 'Content-Workflow und Monetarisierung müssen zum Alltag passen', paragraphs: ['Prüfe, welche Posting-, Messaging-, Bundle-, Preis- oder Segmentierungsfunktionen du wirklich brauchst. Mehr Funktionen sind nur dann wertvoll, wenn sie regelmäßig genutzt werden und deinen Workflow vereinfachen.', 'Notiere deinen typischen Wochenablauf und spiele ihn auf beiden Plattformen durch: Produktion, Planung, Veröffentlichung, Kommunikation, Auswertung und Auszahlung. Kleine Unterschiede können im Alltag wichtiger sein als große Marketingversprechen.'] },
      { title: 'Richtlinien, Gebühren und Auszahlung immer aktuell prüfen', paragraphs: ['Plattformregeln und Gebühren können sich ändern. Verlasse dich bei geschäftskritischen Entscheidungen nicht auf alte Vergleichsartikel. Prüfe aktuelle Terms, Gebührenstruktur, Auszahlungsvoraussetzungen und Content-Regeln direkt in den offiziellen Informationen.', 'Dokumentiere außerdem, welche Daten du exportieren kannst und wie ein Wechsel funktionieren würde. Das reduziert Plattformrisiko, falls sich Bedingungen später ändern.'] },
      { title: 'Eine Multi-Plattform-Strategie kann sinnvoll sein – aber nicht immer', paragraphs: ['Auf mehreren Plattformen präsent zu sein kann Abhängigkeit reduzieren, erzeugt aber zusätzliche Arbeit. Du brauchst mehr Content-Management, mehr Reporting und möglicherweise unterschiedliche Kommunikationsprozesse.', 'Starte lieber mit einer klaren Primärplattform und definiere Bedingungen, unter denen eine zweite Plattform hinzukommt. So vermeidest du, dass beide Accounts halb gepflegt werden.'], bullets: ['Zielgruppe und Markenbekanntheit', 'Interne Discovery', 'Externer Traffic und Conversion', 'Content-Workflow', 'Monetarisierungsfunktionen', 'Richtlinien und Gebühren', 'Analytics und Datenzugang', 'Aufwand einer Multi-Plattform-Strategie'] },
    ],
    checklistTitle: 'Fansly-vs-OnlyFans-Entscheidung', checklist: ['Zielgruppe auf beiden Plattformen geprüft', 'Externen Traffic realistisch eingeschätzt', 'Benötigte Content-Funktionen notiert', 'Monetarisierungsanforderungen festgelegt', 'Aktuelle Gebühren offiziell geprüft', 'Richtlinien und Content-Regeln geprüft', 'Analytics- und Datenbedarf verglichen', 'Primärplattform bewusst gewählt'],
    related: ['onlyfans-guide', 'onlyfans-marketing', 'creator-kennzahlen', 'onlyfans-management-vs-selbst-machen'],
    serviceLinks: [{ href: '/de/creator-management', label: 'Plattformstrategie im Creator Management', text: 'Wir betrachten Plattformwahl als Teil von Positionierung, Distribution, Workflow und Risiko – nicht isoliert.' }],
  },

  'fanvue-vs-onlyfans': {
    slug: 'fanvue-vs-onlyfans',
    category: 'Analyse',
    eyebrow: 'Fanvue vs OnlyFans',
    title: 'Fanvue vs OnlyFans: Plattformwahl nach Zielgruppe, Workflow und Wachstum vergleichen',
    metaTitle: 'Fanvue vs OnlyFans: Vergleich für Creator',
    metaDescription: 'Fanvue vs OnlyFans sinnvoll vergleichen: Zielgruppe, Discovery, Creator-Tools, Monetarisierung, Analytics, Richtlinien und Plattformrisiko.',
    lead: 'Ein Plattformvergleich sollte nicht bei Markenname und Gebühren enden. Für Creator zählen auch Discovery, Workflow, verfügbare Tools, Zielgruppen-Fit, Daten und die Frage, wie abhängig das gesamte Business von einer Plattform wird.',
    shortAnswer: 'Bewerte Fanvue und OnlyFans mit einer eigenen Entscheidungsmatrix. Gewichte Zielgruppe, Markenbekanntheit, Discovery, Workflow, Monetarisierung, Analytics, Richtlinien und Exportmöglichkeiten nach deiner Situation. Prüfe aktuelle Gebühren und Funktionen direkt bei den Plattformen, weil sich Produktdetails schnell ändern können.',
    readingTime: '10 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Dein bestehender Traffic verändert die Entscheidung', paragraphs: ['Wenn du bereits eine starke Community hast, ist die Plattformwahl vor allem eine Conversion- und Workflow-Frage. Wenn du noch Reichweite aufbaust, werden Discovery-Möglichkeiten und die Reibung beim Onboarding neuer Fans wichtiger.', 'Betrachte deshalb nicht nur absolute Nutzerzahlen, sondern deine konkrete Ausgangslage. Ein kleinerer Kanal kann für einen bestimmten Creator sinnvoller sein, wenn Zielgruppe und Produkt dort besser zusammenpassen.'] },
      { title: 'Creator-Tools sind nur wertvoll, wenn sie echte Arbeit sparen', paragraphs: ['Plattformen unterscheiden sich in Automatisierung, Messaging, Analytics, Content-Verwaltung und anderen Creator-Funktionen. Erstelle vor dem Vergleich eine Liste mit Aufgaben, die dich jede Woche tatsächlich Zeit kosten.', 'Bewerte dann, welche Plattform diese Aufgaben vereinfacht. Eine Funktion, die auf einer Marketingseite beeindruckend klingt, hat keinen Wert, wenn sie nicht in deinen Workflow passt.'] },
      { title: 'Discovery und Markenvertrauen gegeneinander abwägen', paragraphs: ['Ein bekannter Markenname kann für neue Nutzer weniger erklärungsbedürftig sein. Alternative Plattformen können dafür eigene Discovery- oder Creator-Funktionen stärker hervorheben. Entscheidend ist, welcher Vorteil in deinem Funnel wichtiger ist.', 'Teste bei ausreichendem Traffic mit klaren Zeiträumen und identischer Positionierung. Nur so kannst du unterscheiden, ob Unterschiede von der Plattform oder von wechselndem Content kommen.'] },
      { title: 'Geschäftskritische Bedingungen direkt bei der Plattform prüfen', paragraphs: ['Gebühren, Payout-Regeln, erlaubte Inhalte und technische Funktionen sind veränderlich. Aktuelle Entscheidungen sollten deshalb immer auf den offiziellen Terms, Help-Centern oder Creator-Dokumentationen beruhen.', 'Speichere dir wichtige Bedingungen und notiere das Prüfdatum. Das macht spätere Reviews einfacher und verhindert, dass du auf veraltete Vergleichstabellen vertraust.'] },
      { title: 'Plane einen Exit, bevor du ihn brauchst', paragraphs: ['Unabhängig von der Plattform solltest du wissen, welche Inhalte, Kontakte, Reports und Arbeitsstände du sichern kannst. Plattformabhängigkeit wird erst dann zum Problem, wenn ein Wechsel ungeplant stattfinden muss.', 'Ein einfacher monatlicher Backup- und Reporting-Prozess hilft dabei, deine eigene Geschäftshistorie unabhängig von einem einzelnen Dashboard zu behalten.'], callout: 'Die beste Plattform ist die, die zu deinem Zielgruppen-Fit und Workflow passt – und aus der du bei Bedarf sauber wieder herauskommst.' },
    ],
    checklistTitle: 'Fanvue-vs-OnlyFans-Vergleich', checklist: ['Eigene Prioritäten gewichtet', 'Zielgruppen-Fit geprüft', 'Discovery-Bedarf eingeschätzt', 'Wöchentliche Workflow-Aufgaben verglichen', 'Aktuelle Gebühren offiziell geprüft', 'Richtlinien und Payout-Bedingungen geprüft', 'Analytics- und Exportmöglichkeiten betrachtet', 'Backup- und Exit-Prozess eingeplant'],
    related: ['fansly-vs-onlyfans', 'onlyfans-guide', 'creator-kennzahlen', 'creator-account-sicherheit'],
    serviceLinks: [{ href: '/de/creator-management', label: 'Plattformstrategie', text: 'Wir wählen Plattformen nicht nach Hype, sondern nach Zielgruppe, Workflow, Funnel und operativer Stabilität.' }],
  },
};

export const pillarGuideList = Object.values(pillarGuides);
