import type { SearchDemandGuidePage } from '@/lib/search-demand-guide-pages';

export const searchDemandGuides3: Record<string, SearchDemandGuidePage> = {
  'onlyfans-account-abgelehnt': {
    slug: 'onlyfans-account-abgelehnt',
    category: 'Einstieg',
    eyebrow: 'Account abgelehnt',
    title: 'OnlyFans Account abgelehnt: so findest du den Grund statt immer wieder blind neu einzureichen',
    metaTitle: 'OnlyFans Account abgelehnt: Ursachen & Checkliste',
    metaDescription: 'OnlyFans Account oder Verifizierung abgelehnt? So prüfst du Dokumente, Social-Media-Nachweise, Datenkonsistenz und Support systematisch.',
    lead: 'Mehrfache Ablehnungen sind für neue Creator besonders frustrierend. Häufig hilft es nicht, denselben Antrag immer wieder abzuschicken, sondern die konkrete Rückmeldung in einzelne Prüfpunkte zu zerlegen.',
    shortAnswer: 'Sichere zuerst die genaue Ablehnungsnachricht. Prüfe dann nacheinander Lesbarkeit des Ausweises, Übereinstimmung deiner persönlichen Daten, Qualität der Identitätsfotos und gegebenenfalls die geforderten Social-Media-Nachweise. Ändere immer nur den beanstandeten Punkt und dokumentiere jede Einreichung. Wenn die Rückmeldung unklar bleibt, wende dich über den offiziellen Support mit Screenshots und einer kurzen Chronologie an OnlyFans.',
    readingTime: '9 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Die Ablehnungsnachricht ist dein Ausgangspunkt', paragraphs: ['Bevor du neue Fotos machst oder Daten änderst, speichere die exakte Rückmeldung. Unterschiedliche Meldungen weisen auf unterschiedliche Prüfbereiche hin – zum Beispiel Dokumentqualität, Identitätsabgleich oder zusätzliche Social-Media-Nachweise.', 'Erstelle eine kurze Liste: Was wurde beanstandet, was hast du bereits geändert und wann wurde erneut eingereicht? So vermeidest du, nach fünf Versuchen selbst nicht mehr zu wissen, welche Variante geprüft wurde.'] },
      { title: 'Dokumentfotos müssen technisch sauber sein', paragraphs: ['Community-Berichte zeigen immer wieder Ablehnungen wegen unscharfer oder schlecht lesbarer Ausweisfotos. Nutze gleichmäßiges Licht, vermeide Spiegelungen und fotografiere das Dokument vollständig und ohne Filter.', 'Wenn die Frontkamera Details weichzeichnet oder spiegelt, kann ein Foto mit der rückseitigen Kamera beziehungsweise durch eine zweite Person technisch besser sein. Entscheidend ist nicht die Kamera selbst, sondern dass Gesicht und Dokument eindeutig und unverfälscht erkennbar sind.'] },
      { title: 'Social-Media-Nachweise müssen wirklich überprüfbar sein', paragraphs: ['Aktuelle Creator-Berichte zeigen, dass OnlyFans teilweise zusätzliche öffentliche Social-Media-Nachweise verlangt. Ein verlinkter Account hilft nur, wenn er für die Prüfung tatsächlich zugänglich ist und nachvollziehbar zur Person gehört.', 'Wenn die Plattform ausdrücklich weitere Social-Media-Verifikation verlangt, folge genau dieser Anweisung. Erfinde keine Aktivität und kaufe keine Follower – der Zweck ist Identitätsplausibilität, nicht Reichweite.'] },
      { title: 'Nicht fünf Dinge gleichzeitig ändern', paragraphs: ['Wenn du Ausweisfoto, Name, Social-Media-Link und Profilinformationen gleichzeitig änderst, weißt du später nicht, welcher Punkt das Problem gelöst oder verschärft hat.', 'Gehe deshalb wie bei einem technischen Fehler vor: eine Hypothese, eine Änderung, eine neue Prüfung. Das kostet weniger Zeit als hektische Komplettumbauten.'] },
      { title: 'Wann du den Support einschalten solltest', paragraphs: ['Wenn du dieselbe allgemeine Ablehnung trotz sauberer Korrektur mehrfach erhältst, sammle Screenshots, Datum der Versuche und die konkret verwendeten Nachweise. Schreibe anschließend eine kurze Support-Anfrage ohne lange Vorgeschichte.', 'Versende Identitätsdokumente nur über offizielle Upload- oder Support-Wege. Dritte, Agenturen oder vermeintliche Helfer benötigen keine Kopie deines Ausweises, um eine Ablehnung „für dich zu lösen“.'], callout: 'Behandle jede Ablehnung wie einen einzelnen Prüfpunkt – nicht wie ein Signal, alles am Account gleichzeitig zu verändern.' },
    ],
    checklistTitle: 'Vor der nächsten Einreichung',
    checklist: ['Ablehnungsgrund gespeichert', 'Ausweis vollständig und scharf fotografiert', 'Keine Filter oder Retusche verwendet', 'Stammdaten auf Übereinstimmung geprüft', 'Geforderte Social-Media-Nachweise öffentlich erreichbar', 'Nur den beanstandeten Punkt geändert', 'Versuch dokumentiert', 'Bei wiederholter Ablehnung Support-Chronologie vorbereitet'],
    related: ['onlyfans-verifizierung', 'creator-account-sicherheit', 'onlyfans-starten', 'onlyfans-anonym-starten'],
    serviceLinks: [{ href: '/de/creator-management', label: 'Sauberes Creator Setup', text: 'Wir helfen bei Struktur, Zugängen und Prozessen – Identitätsprüfung und Freigabe bleiben beim Creator und der Plattform.' }],
    sources: [
      { label: 'Creator-Diskussion: zusätzliche Social-Media-Verifikation', href: 'https://www.reddit.com/r/onlyfansadvice/comments/1vn8pgi/onlyfans_keeps_rejecting_my_account_approval/', note: 'Aktuelle Community-Erfahrungen, keine offizielle Plattformregel' },
      { label: 'Creator-Diskussion: wiederholte Verifizierungsprobleme', href: 'https://www.reddit.com/r/onlyfansadvice/comments/1uue7kt/what_am_i_doing_wrong_with_verifications/', note: 'Community-Erfahrungen zu Fotoqualität und erneuter Einreichung' },
    ],
  },

  'onlyfans-chargeback-was-tun': {
    slug: 'onlyfans-chargeback-was-tun',
    category: 'Sicherheit',
    eyebrow: 'Chargeback',
    title: 'OnlyFans Chargeback: was du als Creator sofort dokumentieren und künftig besser absichern kannst',
    metaTitle: 'OnlyFans Chargeback: Was tun als Creator?',
    metaDescription: 'OnlyFans Chargeback erhalten? Beweise sichern, Transaktion dokumentieren, Support kontaktieren und künftige Risiken bei Custom Content strukturierter handhaben.',
    lead: 'Ein Chargeback fühlt sich besonders unfair an, wenn Content bereits geliefert wurde. Du kannst Rückbuchungen nicht vollständig verhindern, aber du kannst Beweise, Abläufe und Risikogrenzen deutlich besser organisieren.',
    shortAnswer: 'Sichere sofort Chatverlauf, Kaufdetails, Zeitstempel und den Nachweis, dass vereinbarter Content geliefert wurde. Melde den Vorgang über den offiziellen Plattform-Support und behalte die Transaktion in deiner Buchhaltung im Blick. Für die Zukunft helfen klare Leistungsbeschreibungen, dokumentierte Übergaben und interne Limits bei ungewöhnlich hohen Einzelbestellungen. Eine Erstattung oder erfolgreiche Anfechtung lässt sich trotzdem nicht garantieren.',
    readingTime: '9 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Erst Beweise sichern, dann reagieren', paragraphs: ['Wenn eine Rückbuchung auftaucht, speichere den gesamten relevanten Verlauf: Bestellung, Preis, vereinbarte Leistung, Versand beziehungsweise Freischaltung und Zeitpunkt der Kommunikation.', 'Screenshots sind besser als Erinnerung. Benenne Dateien nachvollziehbar und speichere sie außerhalb des Chats, solange der Verlauf noch verfügbar ist.'] },
      { title: 'Unterscheide Plattformfall und Bankfall', paragraphs: ['Als Creator solltest du nicht versuchen, einen Fan außerhalb der Plattform direkt finanziell unter Druck zu setzen. Kläre den Vorgang über die vorgesehenen Support- und Zahlungswege.', 'Dokumentiere außerdem, wie sich die Rückbuchung auf deinen Plattform-Saldo auswirkt. Das ist für dein eigenes Reporting und gegebenenfalls die Buchhaltung relevant.'] },
      { title: 'Custom Content braucht einen sauberen Auftragsprozess', paragraphs: ['Je größer und individueller eine Bestellung ist, desto wichtiger wird eine klare schriftliche Zusammenfassung vor der Produktion: Umfang, Format, Lieferzeit und Preis.', 'Das verhindert nicht jeden Chargeback, reduziert aber Missverständnisse und gibt dir einen nachvollziehbaren Leistungsnachweis. Bei ungewöhnlich hohen Bestellungen darfst du intern zusätzliche Prüf- oder Freigabeschritte vorsehen, ohne die Plattformregeln zu umgehen.'] },
      { title: 'Nicht jeden großen Kauf automatisch als guten Kunden werten', paragraphs: ['Ein sehr hoher Erstkauf kann positiv sein, ist aber auch ein Grund, nicht sofort unbegrenzt zusätzlichen Aufwand zu produzieren. Risikomanagement bedeutet, außergewöhnliche Transaktionen bewusst zu behandeln.', 'Lege intern fest, ab welcher Bestellgröße du die Kommunikation noch einmal zusammenfasst oder Lieferungen in klar dokumentierte Schritte teilst.'] },
      { title: 'Chargebacks gehören in deine Kennzahlen', paragraphs: ['Wenn Rückbuchungen regelmäßig auftreten, betrachte sie nicht nur als Ärgernis, sondern als Kostenposition. Tracke Anzahl, Betrag, betroffene Produkte und Muster.', 'So erkennst du, ob bestimmte Angebotsarten, Traffic-Quellen oder besonders große Einzelbestellungen überproportional betroffen sind.'], callout: 'Das Ziel ist nicht, jeden Chargeback vorherzusagen. Das Ziel ist, im Streitfall nicht ohne Dokumentation dazustehen.' },
    ],
    checklistTitle: 'Bei einem Chargeback sichern',
    checklist: ['Transaktionsdaten gespeichert', 'Chatverlauf gesichert', 'Leistungsbeschreibung dokumentiert', 'Liefernachweis gespeichert', 'Support-Fall eröffnet', 'Auswirkung auf Saldo notiert', 'Buchhaltung informiert', 'Risikoregel für künftige Großbestellungen geprüft'],
    related: ['creator-account-sicherheit', 'onlyfans-ppv-strategie', 'onlyfans-auszahlung-probleme', 'creator-kennzahlen'],
    serviceLinks: [{ href: '/de/creator-management', label: 'Saubere Creator Operations', text: 'Klare Prozesse für Custom Content, Reporting und Support-Fälle reduzieren Chaos, auch wenn Rückbuchungen nie vollständig vermeidbar sind.' }],
    sources: [
      { label: 'Creator-Diskussion: Custom Content und Chargeback', href: 'https://www.reddit.com/r/onlyfansadvice/comments/1vhgy35/man_asked_for_a_bunch_of_custom_content_than/', note: 'Community-Erfahrung zu Rückbuchungen nach individuellen Bestellungen' },
    ],
  },

  'onlyfans-ppv-wird-nicht-gekauft': {
    slug: 'onlyfans-ppv-wird-nicht-gekauft',
    category: 'Analyse',
    eyebrow: 'PPV verkauft nicht',
    title: 'OnlyFans PPV wird nicht gekauft: so findest du heraus, ob Preis, Teaser, Zielgruppe oder Timing das Problem ist',
    metaTitle: 'OnlyFans PPV wird nicht gekauft: Ursachen & Tests',
    metaDescription: 'OnlyFans PPV verkauft sich nicht? Prüfe Zielgruppe, Teaser, Preis, Frequenz, Timing und Käuferquote mit einem einfachen Testplan.',
    lead: 'Wenn PPV-Nachrichten geöffnet, aber kaum gekauft werden, hilft meist kein weiterer Massenversand. Besser ist ein sauberer Funnel-Check: Wer bekommt das Angebot, was wird versprochen und wie groß ist die Kaufhürde?',
    shortAnswer: 'Bewerte PPV nicht nur nach Umsatz. Miss zuerst Empfänger, Öffnungen beziehungsweise Reaktionen, Käufe und Umsatz pro Empfänger. Teste anschließend immer nur eine Variable: Teaser, Preis, Inhaltstyp, Zielgruppensegment oder Zeitpunkt. Wenn dieselbe Nachricht an alle Fans geht, obwohl ihre Interessen und Kaufhistorie unterschiedlich sind, ist Segmentierung oft der größere Hebel als ein pauschaler Preisnachlass.',
    readingTime: '10 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Beginne mit der Käuferquote, nicht mit deinem Bauchgefühl', paragraphs: ['Notiere pro Versand mindestens Empfängerzahl, Käufe und Umsatz. Wenn möglich, ergänze Reaktionen oder Klicksignale. So wird sichtbar, ob ein Angebot grundsätzlich funktioniert oder nur bei wenigen besonders aktiven Fans.', 'Vergleiche mehrere Sendungen über einen längeren Zeitraum. Einzelne schlechte Tage sagen wenig aus.'] },
      { title: 'Der Teaser muss den Wert erklären, ohne alles zu verschenken', paragraphs: ['Ein Teaser sollte genug Kontext geben, damit jemand weiß, was ihn erwartet. Vage Formulierungen wie „something special“ erzeugen weniger Orientierung als ein klarer Hinweis auf Format, Thema oder Besonderheit.', 'Vermeide gleichzeitig Übertreibungen. Wenn das Versprechen größer klingt als der gelieferte Inhalt, schadet das späteren Käufen und der Retention.'] },
      { title: 'Preis ist nur eine Variable', paragraphs: ['Ein schwaches Angebot wird durch einen niedrigeren Preis nicht automatisch stark. Teste Preis erst dann, wenn Inhalt und Positionierung verständlich sind.', 'Wenn du Preise testest, halte Inhalt und Zielgruppe möglichst konstant. Sonst kannst du aus dem Ergebnis nichts lernen.'] },
      { title: 'Segmentiere nach Verhalten statt alle gleich anzuschreiben', paragraphs: ['Neue Fans, wiederkehrende Käufer und Fans ohne bisherige Käufe befinden sich in unterschiedlichen Situationen. Dieselbe Nachricht kann deshalb sehr unterschiedlich wirken.', 'Eine einfache Segmentierung reicht: aktive Käufer, neue Subscriber, lange inaktive Fans. Passe Frequenz und Angebot an, statt jeden Kontakt identisch zu behandeln.'] },
      { title: 'Zu viel PPV kann den Kanal selbst entwerten', paragraphs: ['Wenn fast jede Nachricht ein Verkauf ist, sinkt die Aufmerksamkeit für einzelne Angebote. Plane deshalb normale Kommunikation und Verkaufsnachrichten als getrennte Funktionen.', 'Miss nicht nur kurzfristigen PPV-Umsatz, sondern auch Kündigungen und langfristige Aktivität. Ein aggressiver kurzfristiger Verkauf kann auf Dauer teuer werden.'], callout: 'Wenn PPV nicht gekauft wird, ändere nicht gleichzeitig Preis, Teaser, Content und Versandzeit – sonst lernst du nichts.' },
    ],
    checklistTitle: 'PPV-Testplan',
    checklist: ['Empfängerzahl erfasst', 'Käufe und Umsatz dokumentiert', 'Teaser konkret genug', 'Inhalt und Versprechen stimmen überein', 'Zielgruppen segmentiert', 'Nur eine Variable pro Test geändert', 'Frequenz der Verkaufsnachrichten geprüft', 'Retention neben Umsatz beobachtet'],
    related: ['onlyfans-ppv-strategie', 'onlyfans-preise-festlegen', 'onlyfans-subscriber-halten', 'creator-kennzahlen'],
    serviceLinks: [{ href: '/de/onlyfans-management', label: 'Monetarisierung mit System', text: 'Wir verbinden Content, Segmentierung, Pricing und Retention zu einem messbaren Ablauf statt einzelne PPVs isoliert zu optimieren.' }],
  },

  'onlyfans-subscriber-verlaengern-nicht': {
    slug: 'onlyfans-subscriber-verlaengern-nicht',
    category: 'Analyse',
    eyebrow: 'Keine Verlängerung',
    title: 'OnlyFans Subscriber verlängern nicht: so analysierst du Retention statt nur neue Fans nachzukaufen',
    metaTitle: 'OnlyFans Subscriber verlängern nicht: Retention verbessern',
    metaDescription: 'OnlyFans Subscriber verlängern nicht? Erwartungen, Posting-Rhythmus, Preis, Kommunikation und Traffic-Qualität systematisch prüfen.',
    lead: 'Neue Subscriber zu gewinnen ist sichtbar. Verlängerungen zu verlieren fällt oft erst später auf. Gerade deshalb gehört Retention zu den wichtigsten Kennzahlen eines nachhaltigen Creator-Accounts.',
    shortAnswer: 'Prüfe zuerst, welche Subscriber überhaupt verlängern, aus welchen Quellen sie kamen und welche Erwartung beim Einstieg gesetzt wurde. Häufige Ursachen für schwache Retention sind unklare Versprechen, inkonsistenter Content, zu starke Verkaufskommunikation, ein unpassendes Preis-Leistungs-Verhältnis oder Traffic mit sehr geringer Kaufabsicht. Verbessere nicht alles gleichzeitig, sondern arbeite den größten Engpass zuerst ab.',
    readingTime: '10 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Retention beginnt vor dem ersten Abo', paragraphs: ['Wenn dein Marketing etwas anderes verspricht als das Profil tatsächlich liefert, entsteht die Kündigung bereits beim Einstieg. Deshalb sollten Bio, Teaser und Content denselben Erwartungsrahmen setzen.', 'Besonders aggressive Rabatte können viele Erstabschlüsse bringen, deren langfristige Bindung aber schwach ist. Bewerte Kampagnen deshalb nach Verlängerungen und nicht nur nach neuen Abos.'] },
      { title: 'Konstanz ist wichtiger als tägliche Maximalleistung', paragraphs: ['Subscriber müssen nicht jeden Tag dieselbe Menge Content erhalten. Sie sollten aber verstehen können, welches Niveau und welcher Rhythmus verlässlich ist.', 'Ein realistischer Plan, den du über Monate halten kannst, ist für Retention wertvoller als eine extrem aktive Startphase mit anschließendem Einbruch.'] },
      { title: 'Verkaufsdruck kann Vertrauen verbrauchen', paragraphs: ['Wenn Chats und Posts überwiegend aus zusätzlichen Angeboten bestehen, kann sich ein bezahltes Abo trotz guter Einzelinhalte unvollständig anfühlen.', 'Definiere deshalb, welchen eigenständigen Wert das Abo liefert und welche Extras optional bleiben. Diese Trennung sollte bereits in der Kommunikation erkennbar sein.'] },
      { title: 'Traffic-Qualität bestimmt Retention mit', paragraphs: ['Ein Subscriber aus einem sehr breit gestreuten Rabatt-Funnel verhält sich oft anders als jemand, der dich schon länger über Social Media verfolgt. Segmentiere deshalb Retention nach Quelle, wenn dein Tracking das zulässt.', 'So erkennst du, ob das Problem wirklich auf dem Profil liegt oder bereits bei der Akquise entsteht.'] },
      { title: 'Baue eine monatliche Retention-Routine', paragraphs: ['Vergleiche Kohorten nach Einstiegsmonat, Kampagne oder Traffic-Quelle. Notiere Verlängerungsrate, Umsatz und auffällige Veränderungen im Content beziehungsweise Pricing.', 'Aus dieser Routine entsteht ein Frühwarnsystem. Wenn Retention sinkt, kannst du reagieren, bevor du den Rückgang nur durch immer mehr Neukunden überdeckst.'], callout: 'Mehr Neukunden sind kein Ersatz für schlechte Retention. Ein stabiler Account braucht beides: Akquise und Bindung.' },
    ],
    checklistTitle: 'Retention prüfen',
    checklist: ['Verlängerungsrate monatlich erfasst', 'Traffic-Quellen getrennt betrachtet', 'Einstiegsversprechen mit tatsächlichem Content verglichen', 'Posting-Rhythmus realistisch', 'Abo-Wert klar von Extras getrennt', 'Rabatt-Kohorten separat gemessen', 'Verkaufsfrequenz geprüft', 'Größten Retention-Engpass definiert'],
    related: ['onlyfans-subscriber-halten', 'onlyfans-tracking-links', 'onlyfans-preise-festlegen', 'creator-kennzahlen'],
    serviceLinks: [{ href: '/de/onlyfans-management', label: 'Retention & Reporting', text: 'Wir betrachten Akquise, Content, Monetarisierung und Verlängerungen gemeinsam, statt nur neue Subscriber zu zählen.' }],
  },

  'reddit-posts-werden-geloescht': {
    slug: 'reddit-posts-werden-geloescht',
    category: 'Wachstum',
    eyebrow: 'Reddit Posts entfernt',
    title: 'Reddit Posts werden gelöscht oder gefiltert: so findest du als Creator den echten Grund',
    metaTitle: 'Reddit Posts werden gelöscht: Creator Checkliste 2026',
    metaDescription: 'Reddit Posts werden entfernt? Subreddit-Regeln, Automod, Spamfilter, Karma, Verifizierung und wiederholte Inhalte systematisch prüfen.',
    lead: 'Creator stoßen auf Reddit häufig an unterschiedliche Community-Regeln, Verifizierungen und automatische Filter. Dass ein Post verschwindet, bedeutet deshalb nicht automatisch einen Plattform-Bann oder „Shadowban“.',
    shortAnswer: 'Prüfe zuerst, ob der Beitrag von Moderator:innen, Automod oder dem Spamfilter entfernt wurde. Lies anschließend die Regeln genau dieses Subreddits, kontrolliere Verifizierungsanforderungen, erlaubte Links, Titelregeln und Mindestanforderungen an Account oder Karma. Vermeide massenhaft identische Posts über viele Communities hinweg. Wenn eine Entfernung unklar bleibt, frage höflich per Modmail nach dem konkreten Grund.',
    readingTime: '10 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Jedes Subreddit hat eigene Regeln', paragraphs: ['Reddit erlaubt Communities, eigene Regeln und Moderationsstandards festzulegen. Ein Post kann deshalb in einem Subreddit erlaubt und im nächsten sofort entfernt werden.', 'Lies vor dem Posten Regeln, angepinnte Beiträge und gegebenenfalls Verifizierungsanweisungen. Gerade Creator-Subreddits haben häufig deutlich strengere Anforderungen als normale Communities.'] },
      { title: 'Automod und Spamfilter können automatisch eingreifen', paragraphs: ['Reddit stellt Moderator:innen automatische Filter und Automoderator-Regeln zur Verfügung. Beiträge können dadurch gefiltert werden, bevor ein Mensch sie überhaupt prüft.', 'Typische Auslöser können bestimmte Domains, Formulierungen, Accountsignale oder Community-spezifische Regeln sein. Du kannst von außen nicht jede Regel kennen – deshalb ist Modmail bei wiederholten unklaren Entfernungen sinnvoll.'] },
      { title: 'Wiederholte Massenposts sind ein Risiko', paragraphs: ['Reddit definiert wiederholte oder unaufgeforderte Masseninteraktionen als Spam und nennt unter anderem massenhaft wiederholte Inhalte als problematisch. Für Creator bedeutet das: nicht dasselbe Bild mit nahezu identischem Text automatisiert in dutzende Communities drücken.', 'Variiere Inhalte sinnvoll, poste nur dort, wo sie thematisch passen, und beteilige dich organisch an Communities. Reichweite sollte aus Relevanz entstehen, nicht aus maximaler Wiederholung.'] },
      { title: 'Karma und Verifizierung sind Community-Hürden, keine universelle Plattformregel', paragraphs: ['Viele NSFW- oder Creator-Communities verlangen Mindestkarma, Accountalter oder eigene Verifizierung. Diese Regeln stammen häufig von den jeweiligen Moderatorenteams.', 'Wenn du sie umgehen willst, riskierst du eher weitere Entfernungen. Besser ist, gezielt Communities auszuwählen, deren Anforderungen du realistisch erfüllen kannst.'] },
      { title: 'Baue eine Subreddit-Datenbank', paragraphs: ['Notiere für relevante Communities Nische, Reichweite, Regeln, Verifizierungsstatus, erlaubte Formate und deine tatsächlichen Ergebnisse. So wird Reddit-Promotion reproduzierbar.', 'Markiere auch, welche Communities zwar viel Reichweite bringen, aber kaum Profilbesuche oder Conversions. Dann verschwendest du weniger Zeit mit reinen Vanity-Zahlen.'], callout: '„Mein Post wurde gelöscht“ ist kein einzelnes Problem. Erst der konkrete Entfernungsgrund entscheidet, was du ändern solltest.' },
    ],
    checklistTitle: 'Vor dem nächsten Reddit-Post',
    checklist: ['Subreddit-Regeln gelesen', 'Verifizierung geprüft', 'Titel- und Linkregeln eingehalten', 'Account-/Karma-Anforderungen geprüft', 'Kein identischer Massenpost', 'Post thematisch passend', 'Entfernungsgrund dokumentiert', 'Bei Unklarheit höfliche Modmail vorbereitet'],
    related: ['onlyfans-auf-reddit-bewerben', 'onlyfans-tracking-links', 'onlyfans-follower-gewinnen', 'social-media-funnel'],
    serviceLinks: [{ href: '/de/creator-management', label: 'Distribution mit System', text: 'Wir strukturieren Kanäle, Regeln, Tracking und Content-Varianten, damit Promotion nicht aus blindem Massenposting besteht.' }],
    sources: [
      { label: 'Reddit Help: Spam', href: 'https://support.reddithelp.com/hc/de/articles/360043504051-Spam', note: 'Offizielle Reddit-Regeln zu wiederholten und unaufgeforderten Aktionen' },
      { label: 'Reddit Help: Wie halte ich meine Community frei von Spam?', href: 'https://support.reddithelp.com/hc/de/articles/28012014962580-Wie-halte-ich-meine-Community-frei-von-Spam', note: 'Offizielle Hinweise zu Filtern, Automod und Community-Regeln' },
      { label: 'Creator-Diskussion zu gestiegenen Reddit-Anforderungen', href: 'https://www.reddit.com/r/onlyfansadvice/comments/1rg9mrb/the_requirements_to_promote_on_here_now_are/', note: 'Community-Erfahrung zu Karma- und Verifizierungsanforderungen' },
    ],
  },

  'onlyfans-agentur-kuendigen': {
    slug: 'onlyfans-agentur-kuendigen',
    category: 'Management',
    eyebrow: 'Agentur kündigen',
    title: 'OnlyFans Agentur kündigen: so planst du Vertrag, Zugänge und Übergabe ohne Chaos',
    metaTitle: 'OnlyFans Agentur kündigen: Übergabe-Checkliste für Creator',
    metaDescription: 'OnlyFans Agentur kündigen: Vertrag prüfen, Fristen dokumentieren, Zugänge sichern, Assets exportieren und operative Übergabe sauber planen.',
    lead: 'Eine Agenturbeziehung zu beenden ist nicht nur eine Kündigungsfrage. Kritisch wird meist die Übergabe: Wer kontrolliert Accounts, E-Mail-Adressen, Dateien, Tracking, Passwörter und laufende Kampagnen?',
    shortAnswer: 'Prüfe zuerst Vertrag, Kündigungsfrist, Vergütung, Rechte und Übergabepflichten. Sichere anschließend alle Accounts, Dateien, Auswertungen und Kommunikationskanäle, auf die du berechtigt zugreifen darfst. Plane einen festen Übergabetag, ändere danach Passwörter und Rollen kontrolliert und dokumentiere offene Zahlungen beziehungsweise Leistungen. Bei Streit über Vertragsauslegung oder Rechte solltest du rechtliche Beratung einholen.',
    readingTime: '11 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Der Vertrag entscheidet über die Kündigung, nicht dein Bauchgefühl', paragraphs: ['Lies Laufzeit, Kündigungsfrist, Formvorgaben, Vergütungsregelungen und eventuelle Nachlaufklauseln. Prüfe außerdem, was zu Accounts, Content-Rechten, Daten und offenen Leistungen geregelt ist.', 'Wenn Formulierungen unklar oder wirtschaftlich relevant sind, lass sie rechtlich prüfen. Ein Creator-Ratgeber kann keine individuelle Vertragsauslegung ersetzen.'] },
      { title: 'Erstelle vor der Kündigung ein Zugangs-Inventar', paragraphs: ['Liste OnlyFans, E-Mail, Social Media, Cloudspeicher, Linktools, Analytics, Passwortmanager und alle weiteren Systeme auf. Notiere, wer aktuell Zugriff hat und wer Eigentümer des jeweiligen Accounts ist.', 'So erkennst du früh, ob kritische Systeme auf Agentur-E-Mail-Adressen oder fremde Telefonnummern registriert wurden.'] },
      { title: 'Daten und Assets brauchen eine geordnete Übergabe', paragraphs: ['Sichere Content-Archive, Redaktionspläne, Reporting, Kampagnendaten, Vorlagen und andere Dateien, soweit sie dir vertraglich zustehen. Verlasse dich nicht darauf, dass nach Vertragsende jeder Link dauerhaft erreichbar bleibt.', 'Definiere einen Übergabeordner und eine Liste der noch fehlenden Unterlagen. Das macht die Kommunikation sachlicher.'] },
      { title: 'Zugänge nicht chaotisch mitten im Betrieb abschalten', paragraphs: ['Plane einen klaren Zeitpunkt für Rollenentzug und Passwortwechsel. Wenn du alles unangekündigt mitten in laufenden Prozessen änderst, können Veröffentlichungen, Zahlungen oder Support-Fälle unnötig hängen bleiben.', 'Nach der Übergabe sollten Wiederherstellungs-E-Mail, Telefonnummer, Zwei-Faktor-Authentifizierung und Passwort vollständig unter deiner Kontrolle liegen.'] },
      { title: 'Offene Leistungen und Zahlungen schriftlich abschließen', paragraphs: ['Fasse zusammen, welche Leistungen bis Vertragsende noch erbracht werden, welche Rechnungen offen sind und welche Kampagnen beendet oder übergeben werden.', 'Eine kurze schriftliche Abschlussübersicht ist wertvoller als verstreute Chatnachrichten. Bei Konflikten über Geld, Rechte oder Fristen solltest du früh professionelle Rechtsberatung einbeziehen.'], callout: 'Der wichtigste Exit-Grundsatz: Dein Creator-Business muss nach der Trennung technisch und operativ weiterlaufen können.' },
    ],
    checklistTitle: 'Agentur-Exit vorbereiten',
    checklist: ['Vertrag und Kündigungsfrist geprüft', 'Form der Kündigung geklärt', 'Zugangs-Inventar erstellt', 'Account-Eigentümer kontrolliert', 'Assets und Reporting gesichert', 'Übergabetermin festgelegt', '2FA und Recovery-Daten zurück unter eigener Kontrolle', 'Offene Zahlungen und Leistungen dokumentiert'],
    related: ['creator-agentur-vertrag-checkliste', 'creator-management-agentur', 'onlyfans-management-vs-selbst-machen', 'creator-account-sicherheit'],
    serviceLinks: [{ href: '/de/creator-management', label: 'Management mit klarer Account-Hoheit', text: 'Saubere Rollen, dokumentierte Prozesse und ein definierter Exit gehören für uns zu professionellem Creator Management.' }],
  },

  'onlyfans-bankverbindung-problem': {
    slug: 'onlyfans-bankverbindung-problem',
    category: 'Analyse',
    eyebrow: 'Bankverbindung',
    title: 'OnlyFans Bankverbindung verschwunden oder lässt sich nicht ändern? So gehst du systematisch vor',
    metaTitle: 'OnlyFans Bankverbindung Problem: Checkliste für Creator',
    metaDescription: 'OnlyFans Bankverbindung verschwunden, Änderung fehlerhaft oder Auszahlung blockiert? Status, Kontodaten, Verifizierung und Support strukturiert prüfen.',
    lead: 'Wenn hinterlegte Bankdaten plötzlich fehlen oder sich nicht speichern lassen, solltest du nicht sofort mehrfach neue Daten eintragen. Zuerst muss klar werden, ob es ein kurzfristiger Plattformfehler oder ein accountbezogenes Problem ist.',
    shortAnswer: 'Sichere zuerst Screenshots der Fehlermeldung und prüfe, ob gleichzeitig andere Creator dasselbe Problem melden. Kontrolliere danach Verifizierungsstatus und hinterlegte Kontoinformationen. Wenn die Oberfläche weiter fehlschlägt, ändere nicht wiederholt Bankdaten, sondern warte bei offensichtlichen Plattformstörungen kurz beziehungsweise eröffne einen offiziellen Support-Fall. Sensible Bankunterlagen nur über verifizierte Plattformkanäle senden.',
    readingTime: '8 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Zuerst klären: Plattformstörung oder nur dein Account?', paragraphs: ['Wenn Bankdaten gleichzeitig bei mehreren Creatorn verschwinden oder ein „internal error“ auftaucht, kann ein vorübergehender technischer Fehler vorliegen. Aktuelle Community-Berichte zeigen genau solche kurzfristigen Vorfälle.', 'Prüfe deshalb zuerst Plattformstatus, aktuelle Support-Hinweise und seriöse Community-Meldungen, bevor du deine gesamte Zahlungsstruktur änderst.'] },
      { title: 'Fehlermeldung und bisherigen Zustand dokumentieren', paragraphs: ['Speichere Screenshots der Zahlungsseite, Fehlermeldung und des letzten erfolgreichen Auszahlungsstatus. Notiere, wann die Bankverbindung zuletzt funktioniert hat.', 'Diese Informationen helfen dem Support deutlich mehr als die Aussage „meine Bank geht nicht“.'] },
      { title: 'Verifizierungs- und Namensdaten mitprüfen', paragraphs: ['Bei accountbezogenen Problemen sollte der Kontoinhaber zu den verifizierten Daten passen. Prüfe außerdem, ob kürzlich persönliche Daten, Adresse oder andere Stammdaten geändert wurden.', 'Ändere keine Daten nur auf Verdacht. Inkonsistente Stammdaten können zusätzliche Prüfungen auslösen.'] },
      { title: 'Keine sensiblen Dokumente an fremde Kontakte senden', paragraphs: ['Bankauszüge und Identitätsdaten sind besonders sensibel. Nutze nur offizielle Support- und Upload-Wege und prüfe E-Mail-Absender beziehungsweise Links sorgfältig.', 'Eine Agentur oder ein fremder „Supporter“ braucht keinen vollständigen Bankzugang, um eine Plattformfehlermeldung zu untersuchen.'] },
      { title: 'Nach der Lösung Auszahlung und Buchhaltung abgleichen', paragraphs: ['Wenn die Bankverbindung wieder funktioniert, kontrolliere die nächste Auszahlung gezielt und gleiche sie mit deinen Plattformreports ab.', 'So stellst du sicher, dass das technische Problem nicht nur optisch verschwunden ist, sondern der Zahlungsfluss tatsächlich wieder stimmt.'], callout: 'Bei Zahlungsfehlern gilt: dokumentieren, Ursache eingrenzen, erst dann ändern.' },
    ],
    checklistTitle: 'Bankproblem eingrenzen',
    checklist: ['Fehlermeldung gespeichert', 'Zeitpunkt des letzten funktionierenden Payouts notiert', 'Hinweise auf Plattformstörung geprüft', 'Verifizierungsstatus kontrolliert', 'Kontoinhaber und Stammdaten geprüft', 'Keine mehrfachen hektischen Änderungen vorgenommen', 'Offiziellen Support bei Bedarf kontaktiert', 'Nächste Auszahlung nach Lösung kontrolliert'],
    related: ['onlyfans-auszahlung-probleme', 'onlyfans-verifizierung', 'creator-account-sicherheit', 'onlyfans-steuern-deutschland'],
    serviceLinks: [{ href: '/de/creator-management', label: 'Operative Kontrolle behalten', text: 'Zahlungs-, Account- und Reportingprozesse sollten so dokumentiert sein, dass der Creator jederzeit den Überblick behält.' }],
    sources: [
      { label: 'Creator-Diskussion: Bankdaten kurzfristig verschwunden', href: 'https://www.reddit.com/r/onlyfansadvice/comments/1uvhh0n/onlyfans_randomly_removed_my_bank_info/', note: 'Aktuelle Community-Erfahrung zu einem offenbar kurzfristigen Plattformfehler' },
    ],
  },

  'instagram-reichweite-eingebrochen-creator': {
    slug: 'instagram-reichweite-eingebrochen-creator',
    category: 'Wachstum',
    eyebrow: 'Instagram Reichweite',
    title: 'Instagram Reichweite eingebrochen? Was Creator prüfen sollten, bevor sie von einem Shadowban ausgehen',
    metaTitle: 'Instagram Reichweite eingebrochen: Creator Diagnose 2026',
    metaDescription: 'Instagram Reichweite plötzlich eingebrochen? Account Status, Empfehlungseignung, Content-Mix, Reels-Signale und Zielgruppe systematisch prüfen.',
    lead: 'Ein Reichweiteneinbruch wird schnell als „Shadowban“ bezeichnet. Für eine brauchbare Diagnose ist dieser Begriff zu unscharf. Wichtiger ist, ob dein Content noch für Empfehlungen geeignet ist und wie sich einzelne Reichweitenquellen verändert haben.',
    shortAnswer: 'Prüfe zuerst Account Status beziehungsweise Hinweise zur Empfehlungseignung und vergleiche Reichweite aus Followern, Explore und Reels über mehrere Wochen. Meta unterscheidet ausdrücklich zwischen erlaubtem Content und Content, der nicht für Empfehlungen geeignet ist. Gerade für Adult Creator kann deshalb nicht nur ein Regelverstoß, sondern auch eingeschränkte Empfehlungseignung Reichweite reduzieren. Analysiere anschließend Content-Mix, Wiederholungen, Hooks und Zielgruppensignale statt sofort einen neuen Account zu starten.',
    readingTime: '10 Min.', published: '2026-09-06', updated: '2026-09-06',
    sections: [
      { title: 'Shadowban ist keine präzise Diagnose', paragraphs: ['Wenn Reichweite sinkt, kann das viele Ursachen haben: Empfehlungseignung, schwächere Performance, weniger veröffentlichter Content, veränderte Zielgruppe oder saisonale Schwankungen.', 'Beginne deshalb mit messbaren Signalen. Vergleiche Reichweite und Interaktionen nach Content-Typ und Quelle statt nur die Gesamtzahl anzusehen.'] },
      { title: 'Empfehlungseignung ist für Creator besonders wichtig', paragraphs: ['Meta erklärt, dass bestimmte Inhalte auf Instagram erlaubt sein können, aber trotzdem nicht in Empfehlungsflächen wie Explore oder Reels verbreitet werden. Das betrifft insbesondere potenziell sensible Inhalte.', 'Für Creator mit erotischer oder stark suggestiver Positionierung ist diese Trennung zentral: Ein Post kann online bleiben und trotzdem deutlich weniger Nicht-Follower erreichen.'] },
      { title: 'Prüfe Account Status und konkrete Hinweise', paragraphs: ['Wenn Instagram dir Hinweise zu Account- oder Content-Status zeigt, arbeite diese zuerst ab. Entferne nicht wahllos dein gesamtes Profil, sondern prüfe einzelne markierte Inhalte und verfügbare Einspruchsmöglichkeiten.', 'Dokumentiere vor Änderungen Screenshots und Kennzahlen, damit du später vergleichen kannst, ob sich die Situation verbessert.'] },
      { title: 'Trenne Reichweitenproblem und Contentproblem', paragraphs: ['Wenn nur einzelne Formate einbrechen, liegt das Problem eher beim Content als beim gesamten Account. Vergleiche Reels, Stories, Feed-Posts und Profilbesuche getrennt.', 'Teste neue Hooks, stärkere Originalität und klarere Themen-Säulen. Meta betont in seinen Empfehlungssystemen Relevanz- und Interaktionssignale; gleichförmige Wiederholungen helfen daher selten langfristig.'] },
      { title: 'Abhängigkeit von einem Kanal reduzieren', paragraphs: ['Selbst ein gut laufender Instagram-Account kann schwanken. Baue deshalb parallel mindestens einen weiteren Discovery-Kanal und eigenes Tracking auf.', 'So wird ein Reichweiteneinbruch zu einem Optimierungsproblem statt zu einem kompletten Geschäftsrisiko.'], callout: 'Frage nicht zuerst „Bin ich shadowbanned?“, sondern „Welche Reichweitenquelle ist eingebrochen – und seit welcher konkreten Änderung?“' },
    ],
    checklistTitle: 'Instagram-Diagnose',
    checklist: ['Account Status geprüft', 'Empfehlungseignung kontrolliert', 'Reichweite nach Quelle verglichen', 'Reels, Feed und Stories getrennt analysiert', 'Markierte Inhalte dokumentiert', 'Content-Änderungen einzeln getestet', 'Profilbesuche und externe Klicks mitgemessen', 'Zweiten Discovery-Kanal aufgebaut'],
    related: ['onlyfans-marketing', 'social-media-funnel', 'onlyfans-follower-gewinnen', 'onlyfans-tracking-links'],
    serviceLinks: [{ href: '/de/creator-management', label: 'Multi-Channel Growth', text: 'Wir bauen Distribution so auf, dass ein einzelner Algorithmus nicht über das komplette Wachstum entscheidet.' }],
    sources: [
      { label: 'Meta: Recommendation Guidelines', href: 'https://about.fb.com/news/2020/08/recommendation-guidelines/', note: 'Meta erklärt den Unterschied zwischen erlaubtem und empfehlungsfähigem Content' },
      { label: 'Meta: Wie KI Empfehlungen auf Instagram beeinflusst', href: 'https://about.fb.com/de/news/2023/06/wie-ki-beeinflusst-was-menschen-auf-facebook-und-instagram-sehen/', note: 'Offizielle Einordnung von Signalen und Empfehlungssystemen' },
    ],
  },
};

export const searchDemandGuideList3 = Object.values(searchDemandGuides3);
